### ISSUE TITLE
`onevent()` does not work with 'click' on audio tags

### ISSUE THREAD

**Issue by mattkcole** [daattali/shinyjs#103]
It would be nice to have something like:
`tags$audio(id = "Audio1", src = "audio.mp3", type = "audio/mp3", controls = T)` in the UI and `onevent("click", "Audio1", r_function())` in the server file in order to run a script, `r_function()` when the audio box is clicked on. It would also be great to be able to run the function when audio events occur such as `onplaying`.

**Comment by daattali** [comment]
Unfortunately it looks like the audio tag is strange and it swallows click events. It's nothing to do with shinyjs, I just tried adding a click handler to an audio tag in pure javascript and it doesn't work. I'm sure there are ways around that, but it won't be supported easily by a general framework like shinyjs.

As for running a function when the onplaying event occurs, again, that's a very specific event that's only applicable to audio tags so I'm not going to add such a specific case to shinyjs. But what you could do is have the `onplaying` event call a javascript function that calls R (using the [Shiny.onInputChange method](https://github.com/daattali/advanced-shiny/tree/master/message-javascript-to-r))

**Comment by mattkcole** [comment]
Great, will try this. Thank you!
