### ISSUE TITLE
Using third party packages from shinyjs

### ISSUE THREAD

**Issue by steveb-cirina** [daattali/shinyjs#108]
Hi

This is more of a question on extending `shinyjs` (or a feature request).  The `shinyjs` package has been great to use and I would like to take advantage of some of its advanced features.

I am comfortable using R Shiny, have started using `shinyjs`, and I am learning to do more with javascript.  I have looked at the examples for using the `extendShinyjs` function as I am interested in using RShiny/shinyjs along with a third party javascript library.  I understand the examples that call a specified javascript function but what isn't clear from the examples is the following:

- Importing/including a third party javascript.
- How to use a third party javascript library (e.g. `dymo.label.framework` in my case; a label printing library) in an RShiny/shinyjs application.

**Question:** Is this possible with `extendShinyjs` (or some other functionality) ?

It may be that I don't yet know enough about javascript.  A simple html/javascript application would potentially be ok, but I need to allow the user to choose a single data line from a loaded csv file to print.  The file and choice handling is easy in RShiny so it is desirable to extend an RShiny application.

Thanks.

**Comment by daattali** [comment]
One of the links I have under FAQ are for how to use extendShinyjs to call functions from 3rd party libraries.  Here's the example: https://github.com/timelyportfolio/sweetalertR/issues/1#issuecomment-151685005

Basically what I did is: in the shiny app, include the javsacript+css of the third party library, and then I defined a shinyjs JS function that simply calls that library. Take a look at that code and study it for a bit, it's as minimal of an example as I can think of

**Comment by steveb-cirina** [comment]
Thanks.  I will have a look.  If I do something useful that is not obvious from the example you give, I will let you know (i.e. to help others).

**Comment by daattali** [comment]
Sounds good, good luck!

---
R-Shiny Consultant
http://deanattali.com/shiny
