### ISSUE TITLE
How to use OnClick action buttons in R ShinyDashBoard

### ISSUE THREAD

**Issue by MohanBunny** [daattali/shinyjs#109]
Hi Daattali,

I am doing sentiment analysis of twitter data using R and shiny dashboard. I have plotted the persentages valueboxes of positive, negative and neutral tweets.

```
valueBoxOutput("positivePercent",width = 3)

output$positivePercent <- renderValueBox({

    positivePercent <- round((nrow(positive)*100)/total)

    valueBox(
      value = paste(positivePercent, "%"),
      subtitle = "Positive", 
      color = "green",
      icon = icon("thumbs-up")
    )
  })
```
And I have shown what are the positive tweets using 

```
tabItem(tabName = "pTweets",
      h2(HTML("<center><b><span style='color: green'>Positive</span> Tweets <i></i></b></center>")),

      tableOutput("positivitweets")
```

Now here I would like when I click that percentage value box then it should show positive tweets below of that box.

I am completely new to HTML and JAVASCRIPT,started to learn.
Can you please suggest me how can i do this.

Thank you

**Comment by daattali** [comment]
Hi @MohanBunny 

I'm sorry but I have a lot of projects going on and unfortunately can't find enough time to provide personalized support. If you find a bug in shinyjs I'd be happy to discuss it and fix it, but if you you need support then I recommend asking on StackOverflow.

Good luck!
