### ISSUE TITLE
Allow shinyjs functions to be run on any selector, not just by id

### ISSUE THREAD

**Issue by daattali** [daattali/shinyjs#11]
for example, it could be useful to want to disable or hide all elements with a given class instead of just doing it by ID

**Comment by daattali** [comment]
implemented for `hide`/`show`/`toggle` but not for `enable`/`disable` because I haven't ran into a usecase for that yet

**Comment by larryhengl** [comment]
hi @daattali , this is similar to #69 , but I've got a usecase for an onclick event handler for a class of icons, rather than on a single elementid.  i haven't looked deeply into the source, but what would be the hurdles to implementing any selector to the on* event funcs?

thanks for the lib!!

**Comment by daattali** [comment]
@larryhengl I implemented the selector support for ALL functions in shinyjs a long time ago, but not to onclick (or onevent, they're the same thing really) because it's not possible, at least I don't see how it's possible.  Onclick took me several months of thinking to figure out how to even implement it, but unfortunately I can't think of any way to support it being generic enough that it could be applied to any element. I do come back to this issue in my mind every now and then because I do want to support it, but I don't know how.  You're welcome to take a look and see if you can think of something!

**Comment by micahwilhelm** [comment]
Perhaps you can try the following workaround. 
I wanted to have the header title of my shiny dashboard (rather than just the toggle icon) toggle the collapsable left sidebar.
` shinyjs::runjs('$(document).on("click", ".main-header .logo", function() { $("body").toggleClass("sidebar-collapse"); });') # no selector in onclick()`
