### ISSUE TITLE
Resetting a fileInput

### ISSUE THREAD

**Issue by rhaydock** [daattali/shinyjs#112]
The reset() function appears to  have stopped working with fileInput, I modified your reset() function example below and everything except the file works.

Thanks!

```
shinyApp( 

  ui = fluidPage(
    useShinyjs(),
    div(
      id = "form",
      textInput("name", "Name", "Dean"),
      radioButtons("gender", "Gender", c("Male", "Female")),
      selectInput("letter", "Favourite letter", LETTERS),
      fileInput("file", "File")
    ),
    actionButton("resetAll", "Reset all"),
    actionButton("resetName", "Reset name"),
    actionButton("resetGender", "Reset Gender"),
    actionButton("resetLetter", "Reset letter"),
    actionButton("resetFile", "Reset file")
  ),
  server = function(input, output) {
    observeEvent(input$resetName, {
      reset("name")
    })
    observeEvent(input$resetGender, {
      reset("gender")
    })
    observeEvent(input$resetLetter, {
      reset("letter")
    })
    observeEvent(input$resetAll, {
      reset("form")
    })
    observeEvent(input$resetFile, {
      reset("file")
    })
  }
)
```

**Comment by daattali** [comment]
Still works for me. I tried using shiny 0.14 and using shiny 1.0.0

What do you mean by "not working"? Start a brand new rstudio session, call `library(shiny);library(shinyjs)`, run your code, select a file, click "reset", and the file name stays in the input?

Please try using the formatting options to format your code in the future

**Comment by rhaydock** [comment]
I am using shiny 0.14.2 and shinyjs 0.9.

Having run the code and encountered the same problem, where the file name stays populated in the input element, I uninstalled and reinstalled the packages and it now works. I assume something didn't work last time I updated and your version 0.8 fix for the reset function hadn't taken effect.

Thanks for your reply and the excellent package!
