### ISSUE TITLE
need help on show/hide a box with shinyjs onclick and  menuSubItem 

### ISSUE THREAD

**Issue by earthcli** [daattali/shinyjs#113]
I have create a box in the UI for passing parameters to the server before run a task(after a runButton is clicked the box should be hidden or collapsed, i have done it through js collapse function), and when the a menuSubItem is clicked, the box should appear again, and exactly the box should be hidden when click menuSubItem again, and show when click again.

I have add the the below code in the server, but it does not works, would you please give me an example:
shinyjs::onclick("menusub1",shinyjs::toggle(id="parinbox",anim = TRUE))

and the useShinyjs() has already been added in the dashboardBody.

Any help is appreciated! Thank you!

**Comment by daattali** [comment]
I'm sorry but I don't have the capacity to solve individual requests for "how do I use shinyjs?" - I suggest you post your question on stackoverflow. And I also suggest you include some code for a working shiny app (a reproducible minimal example) so that it'll be easier for people to help you! Good luck

**Comment by earthcli** [comment]
Thank you all the same.
I have post a question on stackoverflow as well a simple code. 
http://stackoverflow.com/questions/42240485/using-shinyjs-onclick-and-toggle-function-on-a-menusubitem-not-work

any suggestion is appreciated. Thanks again.

**Comment by earthcli** [comment]
Dear daattali,
Thanks for your kindly suggestions before, but I have yet not solved my problem.
I have post a question about "shiny: different tasks with actionButton for each menuSubItems" in the stackoverflow, as well as a complete code,  would you please give me some help, many thanks.

http://stackoverflow.com/questions/42269571/shiny-different-tasks-with-actionbutton-for-each-menusubitems

**Comment by daattali** [comment]
I'm sorry but I have many clients that require my time and I don't have
much free time to help with all the individual requests I receive each day.
If you want my help then you can email me and part my consulting fees, but
assuming you want free help your best bet is online forums :)
