### ISSUE TITLE
display image slider

### ISSUE THREAD

**Issue by kmezhoud** [daattali/shinyjs#114]
Dear @daattali ,
congrats for shinyjs!
It is not really an issue. 
I would like to display image from drive using javascript features.
I focus on this [example]( http://www.jsmadeeasy.com/javascripts/Images/Photo%20Slider/index.htm).

Here my code:
imageFile1/2/3.jpg are the image files.
Any suggestion is welcome.
Thanks,
Karim

```r
library(shiny)

server <- shinyServer(function(input, output) {

  lapply(1:3, function(i){
    output[[paste0('display_image',i)]] <- renderImage({

      image_file <- paste("imageFile",i,".jpg",sep="")

      return(list(
        src = image_file,
        filetype = "image/jpg",
        height = "100%",
        width = "100%"
      ))

    }, deleteFile = FALSE)

  })


})

ui <- shinyUI(fluidPage(
  shinyjs::useShinyjs(),
  titlePanel("Display Image from Drive"),
  sidebarLayout(
    sidebarPanel(
      h2("Hello")
    ),
    mainPanel(
      lapply(1:3, function(i){

        div(style="display:inline-block",
            tags$a(imageOutput(paste0("display_image",i), width=360), href="https://www.google.com" )
        )
      })
    )
  )
))

shinyApp(ui=ui,server=server)


```

**Comment by daattali** [comment]
Hi Karim, since this is not an issue but simply a request to help you write your app, I won't be able to help you. I have too many other projects going on at the moment and have to prioritize my time, sorry! I suggest you post your question on stackoverflow - you did well by providing code that is minimal and reproducible, so it'll be received well there, and there's a good chance someone will help you with your problem :)

**Comment by kmezhoud** [comment]
Sorry for the disturbance and Thanks for your time, 

That means ```shinyjs``` do not has options to manage images using javascipt library?
Thanks,

**Comment by daattali** [comment]
shinyjs has about 15 things that are commonly done in javascript that you can do easily from shiny. Anything else you want to do with javascript, you can use shinyjs to facilitate the communication between shiny <--> javascript
