### ISSUE TITLE
reset() keeps the input value

### ISSUE THREAD

**Issue by palfalvi** [daattali/shinyjs#115]
First of all, thank you for the great package, it saves a lot of time and brain power.

I use the reset() function very often, for example 

```
library(shiny)
library(shinyjs)

ui <- fluidPage(

      mainPanel(
        shinyjs::useShinyjs(),
        fileInput("file", 
                  label = "Upload file", 
                  accept = c(".csv")
                  ),
        actionButton("upload","Upload"),
        actionButton("reset","Reset"),
        tableOutput("table")
         )
      )

server <- function(input, output) {
  
  shinyjs::hide("table")
  
  observeEvent(input$reset, {
    shinyjs::reset("file")
    shinyjs::hide("table")
  }) 
  
  observeEvent(input$upload, {
    file1 <- isolate(input$file)
    data <- read.csv(file1$datapath)
    output$table <- renderTable(data)
    shinyjs::show("table")
  })

  
}

shinyApp(ui = ui, server = server)
```

The problem here is if you first select a valid file, then hit Reset, then Upload, the file still processed and shown, means the input$file value was not reset, just its UI. The expectation would be to erase the input value also. Do you have any solution for this? Thank you in advance.

**Comment by daattali** [comment]
You're right, it doesn't change the actual input value.

File inputs are extremely awkward and unfortunately are very difficult to work with. If you try googling around for ways to reset a file input (not in shiny, even just in general in html) you'll find that it's not something that has been really solved.

So this is the best I could come up with for file inputs - just clearing the input and allowing you to upload another file (or the same file) again. But shiny doesn't allow us to change the value of an input, so I don't think it can be solved unfortunately.

**Comment by palfalvi** [comment]
Ok, Thank you for the quick response, i understand the problem. 
Still much better then nothing, of course.
