### ISSUE TITLE
Disabling 'selectInput' choices

### ISSUE THREAD

**Issue by steveb-cirina** [daattali/shinyjs#116]
Hi

I know how to use `shinyjs` to disable a control (e.g. an entire `selectInput`), however, I was wondering if `shinyjs` has a way to disable select choices in the `selectInput` list based on some condition ? 

Given:

```
selectInput("my_input_choices",
            label = "My Input Choices",
            choices = LETTERS[1:5])
```

how could I `disable` a subset of choices, such as for the letters 'B' and 'C' ?

Thanks.

**EDIT**

FWIW, I did some searching but didn't come up with anything to answer this question.

**Comment by daattali** [comment]
Unfortunately I don't think this is possible to do. The selectize javascript library does not provide (to the best of my knowledge) any way to disable individual options
