### ISSUE TITLE
Turn off "hover" on actionButton using `shinyjs::disable`

### ISSUE THREAD

**Issue by steveb-cirina** [daattali/shinyjs#117]
Hi

It seems that `shinyjs::disable` doesn't turn off `hover` on an `actionButton`, is there a way to do this using `shinyjs` ?

Thanks,
-Steve

**Comment by daattali** [comment]
I'm not sure what you mean by turning off "hover". When a button is disabled, it's greyed out, and it doesn't change when you hover over it (but the mouse cursor changes to a "prohibited" sign). Show me what you see if you think there's a bug?

**Comment by steveb-cirina** [comment]
I was not very clear or thorough.  I did some more testing and it seems that I run into this issue where a button is disabled, but still changes when hovering.  This seems to be an issue when using `shinyjs::disable` with `shinydashboard` and not when doing a basic shiny app (i.e. no `shinydashboard`).

Below are two examples, one NOT using `shinydashboard` (this works as expected) and one with `shinydashboard` (the disabled button changes when hovering).

What I do notice is the following (running the code will likely be faster to see what I am talking about):

**"working" case**
  * background color is white when not hovering; both when disabled and enabled.
  * background color is white when disabled, when both hovering and not hovering.

**"non-working" case** (meaning seeing a change when hovering)
  * background color is light gray when not hovering; both when disabled and enabled.
  * background color is light gray when disabled and not hovering; **turns white when hovering**.

**Question**

Is this a `shinydashboard` or `shinyjs` issue ?

```
## ==> Works as expected <==
library(shiny)
library(shinydashboard)
library(shinyjs)

ui <- shinyUI(
  fluidPage(
    useShinyjs(),
    fluidRow(
      box(
        actionButton('toggle_button', label = 'Toggle Other Button'),
        actionButton("other_button",  label = "Other Button"),
        textOutput("text_id")
      )
    )
  )
)

server <- shinyServer(function(input, output, session) {
  observeEvent(input$toggle_button,{
    shinyjs::toggleState('other_button')
  })
  output$text_id <- renderText({
    paste0("Button Press Count: ", input$other_button)
  })
})

shinyApp(ui = ui, server = server)
```

```
## ==> Has hover "issue" <==
library(shiny)
library(shinydashboard)
library(shinyjs)

ui <- dashboardPage(
  
  # (*) Header
  dashboardHeader(title = "Dashboard Header"),

  # (*) Sidebar
  dashboardSidebar(
    sidebarMenu(
      menuItem("MenuItem",  tabName = "MyTab", selected = TRUE)
    )
  ),

  # (*) Body
  dashboardBody(
    useShinyjs(),
    tabItems(
      tabItem(tabName = "MyTab",
        fluidRow(
          box(
              actionButton('toggle_button', label = 'Toggle Other Button'),
              actionButton("other_button",  label = "Other Button"),
              textOutput("text_id")
          )
        )
      )
    )
  )
)

server <- shinyServer(function(input, output, session) {
  observeEvent(input$toggle_button,{
    shinyjs::toggleState('other_button')
  })
  output$text_id <- renderText({
    paste0("Button Press Count: ", input$other_button)
  })
})

shinyApp(ui = ui, server = server)
```

**Comment by steveb-cirina** [comment]
Also, when I add `style = "background-color:white"` to the `other_button` `actionButton`, then I don't see the issue (as you might expect).  So it appears, as I was getting at in the examples, that the disabling in the `shinydashboard` has this hovering issue because of the background color difference.

It seems that it might require setting the background color for the disabled button be the same when hovering and not hovering. Of course I am not sure how to do this yet.  Can / should `shinyjs` do this ?

**Comment by daattali** [comment]
Ah, I understand your concern. Thanks for the details. I'm sorry to have to close two of your issues in one day, but this is also not something that is up to shinyjs...

shinyjs makes the button disabled by changing the HTML of the button - this has the effect of you literally not being able to click on it. The visual effects are not up to shinyjs, it's generally bootstrap (or whatever other css you have loaded) that determines that. It seems that when shinydashboard is used, there are multiple conflicting CSS libraries that are loaded and their CSS for disabled buttons causes this awkward pairing. You'll notice similar things happen when you use shinythemes - there are some themes where buttons will have weird hover or click states because of clashing CSS files.

The "easy fix" from your end would be to manually assign a CSS to disabled buttons

**Comment by steveb-cirina** [comment]
Thanks for your help in both cases.  I suspected when writing up the example I would have to go the CSS path.
