### ISSUE TITLE
Feature request: add "as is" parameter on onevent and onclick (for using shinyjs inside modules)

### ISSUE THREAD

**Issue by lurodrigo** [daattali/shinyjs#118]
Hi! I'd like to make a suggestion. If we use `onclick` inside a module, it always puts the namespace prefix on the id of the element we are assigning a handler. This is great for most cases, but this is not convenient when we are assigning an event handler to a element that has a specific ID (for example, if we are using custom HTML code). 

My use case was that I needed to create a dynamic list of results based on the search term typed by the user, and then assign an event handler for each of the elements on the list. Each element had the id `result{n}`, where `{n}` is an identifier. When using onclick, it assigns event handlers to `namespace-result{n}` instead, which is not the desired outcome.

My workaround was to simply rename the ids to `{ns("")}result{n}`, but I guess a more elegant solution would be to add a logical argument controlling whether the namespace prefix is to be prepended or not.

**Comment by daattali** [comment]
I see the problem - frankly, I'm surprised this hasn't come up earlier. Are you not running into any other issues with shiny itself by having elements inside a module are not namespaced and that you operate on within the server?

It's unfortunate there's no way to automatically determine if an element was created with a namespace or not... I suppose adding a parameter like you suggest would be ok, as long as it's the last parameter (in order not to break existing API).

I will look into adding it to the next version, but will also be happy to accept a PR

**Comment by lurodrigo** [comment]
Sorry for the long delay! No, I don't run into problem with them as long as the modules are singleton (I use them mainly for composability and modularization, not so much for using them many times). But then, I'm not doing too complex things haha.

**Comment by daattali** [comment]
A similar argument should probably be added to all other functions that use an ID because all the shinyjs functions are meant to work well with modules

**Comment by daattali** [comment]
Note: I just ran into this issue with the hide/show functions, where I had to append the name of a namespace to the div's ID to make it work. So yes, this parameter should support all shinyjs funcs

**Comment by daattali** [comment]
@lurodrigo hi, I've added this feature. Can you please try to download the latest version from github and let me know if this is what you wanted?

**Comment by daattali** [comment]
@lurodrigo after thinking about it some more (and seeing Joe Cheng's opinion), I'm thinking of removing this functionality. Can you tell me a bit more about why you need this? Joe has brought up the good point that this will allow for the sort of external dependencies that modules are trying to **prevent**

**Comment by daattali** [comment]
@lurodrigo I'm going to revert this feature because after talking to Joe Cheng and thinking about it some more, I realize this goes against how modules are meant to work. Modules should be 100% isolated and this `asis` parameter breaks this isolation by having modules have an implicit (rather than explicit) dependency and reach out of their scope.

**Comment by daattali** [comment]
After some more time, I'm going back on my previous decision and I will be adding this functionality.

https://github.com/daattali/shinyjs/commit/f5f57c6c2098d712c0e2cae8ba6c24db52d50fbe
