### ISSUE TITLE
shinyjs::disable has no effect on sliderInput

### ISSUE THREAD

**Issue by dnagirl** [daattali/shinyjs#12]
So far as I can tell, `shinyjs::disable`, `enable` and `toggleState` have no effect on sliderInput widgets. I've posted a test case here: https://gist.github.com/dnagirl/cbf56c87024804e25250 using `disable`.

shiny v0.12.0, shinyjs v0.0.3.3 -- from CRAN repository.

**Comment by dnagirl** [comment]
I just tested this with shinyjs v 0.0.6.3 and the problem is resolved. When will that version be pushed to CRAN?

**Comment by daattali** [comment]
This was part of issue #6 which I fixed several days ago.  It was accepted to CRAN a few days ago so it should either be there now or within the next 24-48 hours.  Let me know if you can't get the new version from CRAN.
