### ISSUE TITLE
Package still installs RStudio addin using shinyjs:::colourPicker()

### ISSUE THREAD

**Issue by JoFAM** [daattali/shinyjs#122]
I installed shinyjs today (may 11, 2017) on the latest version of R (3.4.0) with the latest version of RStudio (1.0.143). It still adds an addin "Colourpicker" to RStudio and when I use it, I get the following warning message:

1: As of August 2016, 'colourPicker()' has been deprecated and has moved to the 'colourpicker' package. Please use the 'colourpicker' package in the future. 

That's quite hilarious :-) I'd say: take your own advice at heart and use the colourpicker package ;-)

**Comment by daattali** [comment]
Thanks @JoFAM , good catch! Will remove in next version
