### ISSUE TITLE
Shinyjs functions do not work when mlogit lib is included

### ISSUE THREAD

**Issue by O4karitO** [daattali/shinyjs#124]
Rather weird issue. 
Some functions stop working when mlogit library is included into the project.
What makes it even weirder is that , for instance, hide function still works, while show function stops working (it just prints the ids to log).
using
shinyjs::show("name")
still works though, but mlogit doesn't have a function with the same name, so don't know why this happens

**Comment by daattali** [comment]
Can you please post a minimal reproducible example?

You can try using the showElement() function instead of show() meanwhile

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
Closing due to lack of response
