### ISSUE TITLE
onclick function only partially works inside plotly graphs

### ISSUE THREAD

**Issue by shosaco** [daattali/shinyjs#129]
Thank you for the great package! I am trying to use the `onclick` function as a workaround to the fact that Plotly's event_data("plotly_clicked") is not changing when clicking the same spot twice. This works when clicking in empty spaces in the plot. It does not trigger when one clicks on a marker drawn by plotly. 

Minimal example:

```r
library(plotly)
library(shinyjs)

ui <- fluidPage(  
  useShinyjs(),
  plotlyOutput("plot")
)
server <- function(input, output, session) {
  output$plot <- renderPlotly({
   mtcars %>% plot_ly(x=~disp, y=~cyl)
 }) 
  onclick(id="plot", print("clicked"))
}
shinyApp(ui, server)
```

**Comment by daattali** [comment]
Unfortunately there's not much that shinyjs can do about that. Clicking on the actual points seems to not fire off an onclick of the plot even if you do it directly in javascript. Either plotly is hijacking the click and not letting the message go through, or something else is done to those points that prevents them from counting as clicks on the plot. But either way, it's completely out of shinyjs' hands, sorry!

**Comment by shosaco** [comment]
Thanks for your comment though!

**Comment by shosaco** [comment]
Hi Dean,

I solved the problem for me with.... guess.... shinyjs :-) I manually override the source of `event_data("plotly_click")` at a certain event (closing a modal in my case). This source is `input[[".clientValue-plotly_click-A']]` (where A is the plotly plot source string). Here is the code just in case:

## ui:
```{r}
extendShinyjs(text = "shinyjs.resetClick = function() { Shiny.onInputChange('.clientValue-plotly_click-A', 'null'); }"),
```

## server:
```{r}
# Reset Plotly clickEvent after Click on Cancel Button (fixed issue that click on same marker doesn't trigger new clickevent)
observeEvent(input$cancel_change, {
     js$resetClick()
})
```

**Comment by shosaco** [comment]
fixed: https://github.com/ropensci/plotly/issues/1043
