### ISSUE TITLE
Bug? Comma inside text in the input choice seems to force reset to deselect the choice.

### ISSUE THREAD

**Issue by philstraforelli** [daattali/shinyjs#130]
Hi Dean,

Sorry to bug you again, but I think I ran into a bug? See the code below:

     library(shiny)
     library(shinyjs)

     ui <- fluidPage(
	     useShinyjs(),
     	sidebarLayout(
	     	sidebarPanel(
		     	checkboxGroupInput("Marital", label = h4("Marital Status"), 
		     		choices = c("Married/Living common-law", 
			     		"Single (not in a relationship)", 
				     	"In relationship, but not living together", 
			     		"Prefer not to answer"), 
			     	selected = c("Married/Living common-law", 
		     			"Single (not in a relationship)", 
				     	"In relationship, but not living together", 
				     	"Prefer not to answer")),
			     actionButton("Reset", "Reset", icon("repeat"), class = "btn-primary")
	     	),
	     	mainPanel()
	     )
     )

     server <- function(input, output) {
	     observeEvent(input$Reset, {
	     	reset("Marital") 
	     })
     }

     shinyApp(ui = ui, server = server)

On my end, when I click on the reset button, the "In relationship, but not living together" option gets deselected. It seems that the issue goes away if you remove the comma inside the text.

**Comment by daattali** [comment]
You indeed found a bug! Without looking into it yet I think I know what's going on. Will fix for next version

Thanks for the report

**Comment by daattali** [comment]
fixed
