### ISSUE TITLE
Moving shinyjs.js to a different folder

### ISSUE THREAD

**Issue by TomWeishaar** [daattali/shinyjs#144]
As you suggested in your excellent article on server setup with Digital Ocean, my setup includes an nginx web server as well as Shiny-Server. I'd like to serve all static files, including javascript files, with nginx rather than using Shiny-Server's www folder. I changed the link to the extendShinyjs() function and I've tested that the new link actually serves the file, but shinyjs still dies with a "cannot find javascript file at www/shinyjs.js" error. I'm not sure if this is an issue with the software or if I've missed another place to change the link.

**Comment by daattali** [comment]
That's an interesting problem I haven't seen anyone try to do before. I'm
not super competent with web servers and issues like this but hopefully
I'll be able to spot the problem. Could you post a repriducible example,
which means also show the relevant bits of the nginx config and whatever
else is needed

**Comment by TomWeishaar** [comment]
You can see the nginx config file and additional details at http://www.open-meta.org/technology/how-to-configure-nginx-and-shiny-server-for-a-lemrs-stack/

The shinyjs.js file is at http://dev.open-meta.org/js/shinyjs.js

I get the error after removing the www folder from the app folder. You can see the error at http://dev.open-meta.org/app/

In Shiny-Server terms, I'm trying to use an app folder rather than a site folder, but the blog post I refer to explains that.

**Comment by daattali** [comment]
Thanks for the details! I tried giving that article a quick read but it's not exactly a minimal reproducible example (which is awesome for someone wanting a thorough tutorial, but I'm just looking for the simplest way to replicate the issue). It makes a reference to previous blog posts and has a lot of extra stuff. I'm also not sure what is meant by an app folder vs a site folder (are you referring to one of the [hosting models](http://docs.rstudio.com/shiny-server/#hosting-model)?).

That error makes it sound like R can literally not find the file. If you look at the source of the error: https://github.com/daattali/shinyjs/blob/f50bcf9d3023cbaa27506e864ab3f4e6897edcc6/R/extendShinyjs.R#L280 it's resulting from a negative result to `file.exists(script)`. Perhaps the wording directory isn't what you expect so the relative path needs to change? Maybe the file is not readable? Maybe permission issues? Perhaps it's simply not exposed as a resource? I'm not quite sure. If you're keen on helping debug, you could download shinyjs source code and try to debug from within those lines. That's asking a lot of you, I know, but unfortunately I can't really give out much more advice at this point

**Comment by TomWeishaar** [comment]
Dean - In retrospect, this looks like my misunderstanding. In the big picture, javascript runs on a browser, not on a server. In traditional HTML, there are lines in the header that give the browser URLs to javascript files that need to be loaded (same for CSS files) and that's the mental model my question was based on. 
But I suspect now that with Shiny, the javascript files are handed to Shiny, which puts them on the browser, which is a totally different model and makes my question moot. 

I thought I could give extendShinyjs() a URL, (_extendShinyjs("http://dev.open-meta.org/js/shinyjs.js")_), but and delete the www folder, but if the correct way to think about this is that Shiny sends the javascript to the browser, then extendShinyjs would need a file path, not a URL.

Tom

**Comment by daattali** [comment]
Ah yes, you're correct - it expects a file path on the local file system. Although I don't see any reason it has to stay this way. If you'd like, it's likely possible to allow `extendShinyjs()` to take in either a path or a URL. If you see the value in that, could you open a separate issue for that? (And I'd welcome a PR too if you ever find the time!)

**Comment by TomWeishaar** [comment]
I need to play with this some more now that I understand what's going on. I'm not sure whether there's any value to going down this path, er.. URL.

**Comment by daattali** [comment]
I'm going to close this issue, if you do find there's a bug with shinyjs feel free to reopen

**Comment by TomWeishaar** [comment]
Dean - Agreed. Also, since my comment above that "javascript runs on a browser" I've learned that what the V8 package does is allow R to run javascript code. So there's another mental model I had to update. - Tom
