### ISSUE TITLE
how to use shinyjs in rmd shiny_prerendered

### ISSUE THREAD

**Issue by Kvit** [daattali/shinyjs#149]
Could you specify where /how  (which chunk / context) to include statement useShinyjs(rmd = TRUE) when using shiny_prerendered runtime?
Thanks,

**Comment by daattali** [comment]
I'm afraid I haven't looked into that so I don't have an answer. If you, or
anyone else, uses shinyjs in prerendered shiny, please do report back to
let others know.

**Comment by Kvit** [comment]
I tried to  useShinyjs(rmd = TRUE)  {r  context="render"} but seems that it's working the first time when document actually rendering, and not the next time.  I don't have detailed knowledge of JS to guess right answer but will try to experiment.

**Comment by daattali** [comment]
To be honest I don't know enough about how prerendered works so it is
possible that currently shinyjs won't work with it. But it's also very
possible it does, I don't know. I would try to use it both with and without
rmd=TRUE, and try placing it both in prerendered and in non prerendered
sections, hopefully one of the combinations will work

**Comment by Kvit** [comment]
Ok, the best I figured is that because shiny_prerendered creates static HTML file for ui  we need to work in shinyjs as with html file: which is

1. copy javascript resource file(s) to system subfolder js/ (see details: http://rmarkdown.rstudio.com/authoring_shiny_prerendered.html#external_resources)

2. Include a reference statement in the document header: <script src="shinyjs/inject.js"></script> . this can be done via YAML header
---
title: "mytitle"
output:
  html_document:
    includes:
       in_header: myheader.html
---
But, I'm stuck trying to pull pieces together, where can I get js resource file: inject.js to place it in resource folder?

**Comment by daattali** [comment]
Thanks @Kvit ! So can you describe exactly what is different between that approach and what I describe to do when using an HTML template [here](https://deanattali.com/shinyjs/advanced#usage-html)? What is shinyjs_header.html, is it a one line HTML document that simply contains ` <script src="shinyjs/inject.js"></script>`?

**Comment by Kvit** [comment]
shinyjs_header.html, is it a one line HTML document that simply contains <script src="shinyjs/inject.js"></script>? - Yes. 
Difference in approach:
1. use of YAML frontmatter to include html in <head>
2. using r chunk with context=server  for statement useShinyjs(html = TRUE) (specifics of shiny_prerendered runtime)

**Comment by daattali** [comment]
Thanks for following up!

**Comment by daattali** [comment]
Thanks for following up! So it works fully, as expected?

**Comment by Kvit** [comment]
it does work, as expected or accidently - I'm not sure :)

**Comment by daattali** [comment]
Great! I'm re-opening so that others will be able to easily find this. I'll close it when it gets incorporated into the docs. Thanks

**Comment by daattali** [comment]
This has been added to the documentation https://deanattali.com/shinyjs/advanced#usage-prerendered

FYI - there's a slightly simpler version of what you came up, that doesn't require creating an extra file.
 
````
```{r, echo=FALSE}
shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))
```
```{r, context="server"}
shinyjs::useShinyjs(html = TRUE)
```
<script src="shinyjs/inject.js"></script>
````

**Comment by Kvit** [comment]
Great, thanks!

Vitali Khvatkov
------------------------------------
direct line: 832-915-2050
cell: 713-459-2262
