### ISSUE TITLE
shinyJS doesn't work in rmd when tabsets are used

### ISSUE THREAD

**Issue by saranshjain29** [daattali/shinyjs#150]
When I use tabsets in my rmd shiny document, shinyjs functions wouldn't work, as soon as I remove tabsets all the functions work just fine. is there a workaround to get shinyjs working with tabsets?

**Comment by daattali** [comment]
I was not aware of such an issue. Shinyjs was developed first and foremost for shiny specifically so it's entirely possible that there are unsolveable bugs when used in rmd as opposed to shiny apps. Could you please include a minimal code sample that reproduces the problem?

**Comment by saranshjain29** [comment]
The following would work (The buttons would get disabled)
```
# Without Tabsets

## Tab 1
` ` `{r, echo=FALSE}

library(shinyjs)
useShinyjs(rmd = TRUE)

actionButton(inputId = "disableButton1",label = "Disable Me")
observeEvent(input$disableButton1,{
  disable(id = "disableButton1")
})

` ` `

## Tab 2
` ` `{r, echo=FALSE}

actionButton(inputId = "disableButton2",label = "Disable Me")
observeEvent(input$disableButton2,{
  disable(id = "disableButton2")
})

` ` `
```

But the following wouldn't:

```
# With Tabsets {.tabset}

## Tab 1
` ` `{r, echo=FALSE}

library(shinyjs)
useShinyjs(rmd = TRUE)

actionButton(inputId = "disableButton1",label = "Disable Me")
observeEvent(input$disableButton1,{
  disable(id = "disableButton1")
})

` ` `

## Tab 2
` ` `{r, echo=FALSE}

actionButton(inputId = "disableButton2",label = "Disable Me")
observeEvent(input$disableButton2,{
  disable(id = "disableButton2")
})

` ` `
```

PS: before running the code, remove the spaces between the backticks

**Comment by daattali** [comment]
Thanks. I'll try to take a look later this week. Have you tried posting to stackoverflow, there's quite a bit of shinyjs knowledge and experience there

**Comment by daattali** [comment]
Try placing the `library(shinyjs); useShinyjs(rmd = TRUE);` outside of the tabset definition, in the beginning of the file

**Comment by daattali** [comment]
@saranshjain29 my suggestion does indeed make it work. Closing this issue

**Comment by daattali** [comment]
This has been added to the documentation https://deanattali.com/shinyjs/advanced#usage-tabbed
