### ISSUE TITLE
Feature Request: buttonGrid

### ISSUE THREAD

**Issue by martinjhnhadley** [daattali/shinyjs#151]
A common feature of a Shiny app is to have a set of grouped buttons, for instance the CFL app here: https://daattali.com/shiny/cfl/

- There's a (single) column of buttons
- Clicking on a button changes the state of a variable via `Shiny.onInputChange` in `www/main.js` 

```JS
$( "#welcome_list" ).on( "click", ".welcome_row", function(x){
    Shiny.onInputChange("gamerowclick", $(this).data("gameinfo"));
  });
```
- The selected button from the group modifies the state of the app

A useful feature for shinyJS would be to group buttons together by a master input variable, and for each button in the group to have a unique id, as follows:

- Master id: input$button.master.id
- Unique button id: input$button.master.id_button.id

# Quasi Example

```r
the_ui <- fluidPage(
  shinyjs::useShinyjs(),
  div(id = "select_game_page",
      buttonGrid(
        button.master.id = "gameid",
        button.contents = list(
          gridButton(
            button.id = "game004",
            button.text = "UK vs US"
          ),
          gridButton(
            button.id = "game006",
            button.text = "DE vs FR"
          )
        ),
        columns = 2
      )),
  
  hidden(div(id = "game_info_page",
             fluidPage(
               datatableOutput("game_info"),
               actionButton("select_another_game",
                            "Select Another Game")
             )))
  
  
)

the_server <- function(input, output){
  
  output$game_info <- renderDataTable({
    
    shinyjs::hide("select_game_page")
    shinyjs::show("game_info_page")
    
    game_data %>%
      filter(game.id == input$gameid) %>%
      datatable()
    
  })
  
  observeEvent(input$select_another_game,
               {
                 shinyjs::hide("game_info_page")
                 shinyjs::show("select_game_page")
               })
  
}

shinyApp(the_ui, the_server)
```

**Comment by daattali** [comment]
That's an interesting idea (except for the mix of camelCase, dot.notation, and snake_case all in one feature!) but it feels more of a core shiny component than a shinyjs (javascript) functionality. I try to keep shinyjs only for things that are mostly javascript rather than feature enhancements to shiny. Does this make sense?

**Comment by martinjhnhadley** [comment]
That makes good sense!

Ah, I thought I'd made sense of notation conventions but I clearly need to put more effort in...

- dots for arguments
- snake_case for shiny input variables
- camelCase for shinyJS functions

Thanks for thinking about this, I'll happily make the feature request against the shiny library instead 👍

**Comment by daattali** [comment]
I'm curious to see what Joe and others will think
