### ISSUE TITLE
custom (module) input not hideable

### ISSUE THREAD

**Issue by fabiangehring** [daattali/shinyjs#154]
When creating a custom input module, this does not seem to behave the same as default inputs. This can be shown in the following repex. When clicking "mainButton" the button disappears as desired. When using a custom button here "moduleButton" I'd expect the same behaviour, but this time the button is not hidden.

```
library(shiny)
library(shinyjs)

testModuleInput <- function(id, label) {
  ns <- NS(id)
  actionButton(ns("testModule"), label)
}

testModule<- function(input, output, session) {
  reactive(input$testModule)
}

ui <- fluidPage(
  tagList(
    shinyjs::useShinyjs(),
    actionButton("mainButton", "MainButton"),
    testModuleInput("moduleButton", "ModuleButton")
  )
)

server <- function(input, output, session) {
  module <- callModule(testModule, "moduleButton")
  
  observeEvent(input$mainButton, {
    shinyjs::hide("mainButton")
  })
  
  observeEvent(module(), {
    shinyjs::hide("moduleButton")
  })
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
I believe this is what you're talking about: https://github.com/daattali/shinyjs/issues/118

After thinking about it at length and talking to Joe, I decided against  allowing this. What you're trying to do is against the principles of modules, it violates the isolation and independence of modules. You can read more about it in that issue.

**Comment by fabiangehring** [comment]
Thx, wasn't aware of the other discussion. This brought me to the workaround which works as desired (see below, for others with the same issue). It's a bit ugly, since you need to know the "inner structure" of the module. 

```
library(shiny)
library(shinyjs)

testModuleInput <- function(id, label) {
  ns <- NS(id)
  actionButton(ns("testModule"), label)
}

testModule<- function(input, output, session) {
  reactive(input$testModule)
}

ui <- fluidPage(
  tagList(
    shinyjs::useShinyjs(),
    actionButton("mainButton", "MainButton"),
    testModuleInput("moduleButton", "ModuleButton")
  )
)

server <- function(input, output, session) {
  module <- callModule(testModule, "moduleButton")
  
  observeEvent(input$mainButton, {
    shinyjs::hide("mainButton")
  })
  
  observeEvent(module(), {
    shinyjs::hide(paste0("moduleButton-testModule")) # Changed here!
  })
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
The more correct approach would be to have the module do this work. The
way you're trying to code it (both this and the previous one) violate the
isolation of modules. Both of them require the main server to try to change
an element inside a module. It's tempting to do because it's simpler code,
but in larger apps reaching into modules like this can become confusing.

**Comment by daattali** [comment]
You can see what Joe said about this here: https://github.com/rstudio/shiny/issues/1891#issuecomment-344384619

Closing this issue
