### ISSUE TITLE
Question: Would it be possible to add `update-input` functionality from your Advanced Shiny repo?

### ISSUE THREAD

**Issue by msummersgill** [daattali/shinyjs#156]
I've found that functionality to be extremely useful, and it would be convenient to have them bundled into `shinyjs` instead of manually adding those files in the directory of each Shiny app I use them on.

My javascript knowledge is practically non-existent, so before I go down a rabbit hole I 'd like to check and make sure there isn't a constraint that makes this technically infeasible (or not sensible).

1. Is it technically feasible to add the functions `updateableInput()`, `updateShinyInput()`, and `updateShinyInputs()` in your [advanced-shiny/update-input](https://github.com/daattali/advanced-shiny/tree/master/update-input) repository to `shinyjs`?
2. _(If the answer to the question is yes)_ Would you you consider a pull request adding these features?

**Comment by daattali** [comment]
Hi @msummersgill , I don't think I'd be adding this to shinyjs as it doesn't go with the general theme of shinyjs. Thank you for asking and suggesting a PR. I may have another package that will have this sort of functionality in the near future, but it's unfortunately not shinyjs material
