### ISSUE TITLE
Busy indicator error

### ISSUE THREAD

**Issue by skhan8** [daattali/shinyjs#157]
The 'ajax-loader-bar.gif' isn't loading on my server (CentOS). Here's an example of running the [app.R](https://github.com/daattali/advanced-shiny/blob/master/busy-indicator/app.R) example.

![image](https://user-images.githubusercontent.com/20211314/37002789-d1ce91f8-2098-11e8-9c6d-f6db9781f611.png)

**Comment by daattali** [comment]
This isn't a shinyjs issue so I'm closing the issue.

I'm not sure if that's a screenshot from RStudio or from a browser, but it's a known issue that images don't show up properly always inside RStudio. If it's a browser screenshot, you can try any other image. Regardless, it's an image issue - not a shiny issue

**Comment by skhan8** [comment]
Thanks! It was both in the browser and from RStudio. I'll take a closer look at the image.

**Comment by daattali** [comment]
It sounds like your app isn't finding the image. Seems like a working
directory issue

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

Want to improve your Shiny skills? Try my new interactive, online video
course *Shiny Case Studies*
<https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies>
