### ISSUE TITLE
Other than AGPL-3 license (Invlaid issue, deleted)

### ISSUE THREAD

**Issue by donarus** [daattali/shinyjs#158]
Hi.

It would be beneficial to use lesser strict licensing than AGPL-3 because this license is not usable for commercial software. It would be beneficial to use some sort of commercial-friendly licence or some sort of custom (paid) license for commercial use. We would like to use the library but we can't distribute our other source code.

**Comment by donarus** [comment]
Sorry, I missed the note about licencing in the description. Closing

**Comment by daattali** [comment]
Feel free to email me if you'd like to purchase a commercial license!
