### ISSUE TITLE
bsDatepicker not working with extendShinyjs

### ISSUE THREAD

**Issue by MathieuMarauri** [daattali/shinyjs#162]
Hello, 

I want to make a daterange input autoclosing after a date is selected. I can succesfully do that if the date range is defined in the ui with the following code. 

```
library('shiny')

shinyApp(
  ui = fluidPage(
    includeScript("code.js"),
    fluidRow(
      column(4, 
             dateRangeInput("dates", label = h3("Date range")),
             verbatimTextOutput("datesOut")
      )
    )
  ), 
  server = function(input, output, session) {
    output$datesOut <- renderPrint({ input$dates })
  }
)
```
And the js code.

```
$(document).ready(function(){

  $('#dates input').bsDatepicker({
    autoclose: true, 
    todayHighlight: true,
    keyboardNavigation: false
  });
  
  $('#dates').attr('onkeydown', 'return false');
  
});
```
But if the daterange is defined in the server through `renderUI` then this does not work as the document is ready before the daterange is actually built (correct me if I am wrong).

I tried to use `shinyjs` to deal with this issue, calling the js code only after the date range is rendered. Here is my code.

```
library('shiny')
library('shinyjs')

jsCode <- "shinyjs.changeDate = function(){
$('#dates input').bsDatepicker({autoclose: true});
$('#dates').attr('onkeydown', 'return false');
}"

shinyApp(
  ui = fluidPage(
    useShinyjs(),
    extendShinyjs(text = jsCode),
    fluidRow(
      column(4, 
             uiOutput(outputId = 'dateui'),
             verbatimTextOutput("datesOut")
      )
    )
  ),
  server = function(input, output, session) {
    output$dateui <- renderUI({
      dateRangeInput("dates", label = h3("Date range"))
    })
    session$onFlushed(function() {
      js$changeDate()
    })
  }
)
```
But the daterange is not autoclosing. I have no idea why the js code woud not work this time and works the previous time. I know that using extendshinyjs is working as I can disable keyboard so my question is more on the reason why bsDatepicker would not work in this case. 

My session info:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyjs_1.0 shiny_1.0.5 V8_1.5     

loaded via a namespace (and not attached):
 [1] compiler_3.4.4  R6_2.2.2        htmltools_0.3.6 tools_3.4.4     curl_3.1       
 [6] yaml_2.1.18     Rcpp_0.12.16    digest_0.6.15   jsonlite_1.5    xtable_1.8-2   
[11] httpuv_1.3.6.2  mime_0.5 
```

Thank you for this package and the articles/tutorials you made. This is really helpful. 

Cheers, 

Mathieu

**Comment by daattali** [comment]
This doesn't seem like a shinyjs issue. It looks like perhaps running these JS lines after the datepicker is already initialized simply doesn't work. I tried running the javascript code manually in the javascript console, and indeed the datepicker functionality did not change. Maybe there's a different API to call to change the functionality of an already initialized date picker. Regardless, this looks like it's purely a datepicker/javascript issue, nothing on shinyjs's end, so I'm closing

**Comment by MathieuMarauri** [comment]
Alright I'll look into that. Thank you.
