### ISSUE TITLE
Box uncollapse based on action button input

### ISSUE THREAD

**Issue by krinaj** [daattali/shinyjs#163]
Hello Dean Attali,

Thanks for making such a great package. I have a question that I posted on stackoverflow. 

https://stackoverflow.com/questions/49659804/r-shinyjs-shinydashboard-box-uncollapse-on-action-button-input

Any suggestions will be appreciated when you get a chance. 

thanks,
Krina

**Comment by daattali** [comment]
GitHub Issues are only for reporting bugs or feature requests. I'm closing this as there is no actual issue. Your stackoverflow question seems well written so I hope someone answers!
