### ISSUE TITLE
selector not working with module because id never null

### ISSUE THREAD

**Issue by floriandeboissieu** [daattali/shinyjs#164]
It is an issue related to #133 .
Based the advanced-shiny busy indicator code, the following code is suppose, on button event, to show the busy indicator, disable the button and show the done indicator. It does nothing, although the exact same example without passing through a module works perfectly.
Inspecting the code I found that id had always a value, actually the id of the module. The id is set in `jsFuncHelper` line 32-36, where the condition `if ("id" %in% names(params))` is always true as it is set in all functions show, hide, etc. (I suppose it was developped with dots at the begining).
Moreover, the even if condition changed to `!is.null(params$id)` it still adds the module id to the button id if created with ns to be seen by observeEvent, and if removing ns (as suggested in #133), the selectors are not working anymore.
Autocompletion is not helping at all as it is disturbing usual way of setting id elsewhere in shiny. It should be removed in my opinion. A way to make it softly would be to add a parameter `autoid=TRUE` that can be set to `FALSE` when one doesn't want id auto completion.

```
library(shiny)
library(shinyjs)
withBusyIndicatorUI <- function(button) {
  id <- button[['attribs']][['id']]
  div(  useShinyjs(debug=T),
        `data-for-btn` = id,
        button,
        span(
          class = "btn-loading-container",
          hidden(
            img(src = "ajax-loader-bar.gif", class = "btn-loading-indicator"),
            icon("check", class = "btn-done-indicator")
          )
        ),
        hidden(
          div(class = "btn-err",
              div(icon("exclamation-circle"),
                  tags$b("Error: "),
                  span(class = "btn-err-msg")
              )
          )
        )
  )
}

# Call this function from the server with the button id that is clicked and the
# expression to run when the button is clicked
withBusyIndicatorServer <- function(buttonId, expr) {
  # UX stuff: show the "busy" message, hide the other messages, disable the button
  doneEl <- sprintf("[data-for-btn=%s] .btn-dsone-indicator", buttonId)
  loadingEl <- sprintf("[data-for-btn=%s] .btn-loading-indicator", buttonId)
  errEl <- sprintf("[data-for-btn=%s] .btn-err", buttonId)
  shinyjs::disable(buttonId)
  shinyjs::show(selector = loadingEl)
  shinyjs::hide(selector = doneEl)
  shinyjs::hide(selector = errEl)
  on.exit({
    shinyjs::enable(buttonId)
    shinyjs::hide(selector = loadingEl)
  })
  
  # Try to run the code when the button is clicked and show an error message if
  # an error occurs or a success message if it completes
  tryCatch({
    value <- expr
    shinyjs::show(selector = doneEl)
    shinyjs::delay(2000, shinyjs::hide(selector = doneEl, anim = TRUE, animType = "fade",
                                       time = 0.5))
    value
  }, error = function(err) { errorFunc(err, buttonId) })
}

# When an error happens after a button click, show the error
errorFunc <- function(err, buttonId) {
  errEl <- sprintf("[data-for-btn=%s] .btn-err", buttonId)
  errElMsg <- sprintf("[data-for-btn=%s] .btn-err-msg", buttonId)
  errMessage <- gsub("^ddpcr: (.*)", "\\1", err$message)
  shinyjs::html(html = errMessage, selector = errElMsg)
  shinyjs::show(selector = errEl, anim = TRUE, animType = "fade")
}


# Test module UI
buttonTestUI <- function(id){
  ns = NS(id)
  # shinyjs::useShinyjs(),
  withBusyIndicatorUI(
    actionButton(ns('goPlot'), 'Go plot')
  )}

# Test module server
buttonTest <- function(input, output, session) {
  observeEvent(input$goPlot, {
    withBusyIndicatorServer(session$ns("goPlot"), {
      for(i in 1:10){
        Sys.sleep(0.1)
      }
    })
  })
}


ui <- fluidPage(
  buttonTestUI("shinyjstest")
)

server <- function(input, output){
  callModule(buttonTest, "shinyjstest")
}

shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
This should work if you use a `selector` instead of `id` for enable/disable. It actually wasn't working until a few minutes ago because of a bug, but now it will work. The selector should be `paste0("#", buttonId)`.

There's also a small bug/typo in your code: `doneEl <- sprintf("[data-for-btn=%s] .btn-dsone-indicator", buttonId)` has `btn-dsone-indicator` (notice the extra `s` in there).

I think you were hoping to be able to do this without using a selector and by just using an id. This will not work because shinyjs tries to be smart and assume that IDs given to it are not namespaced. You can see a discussion about this and about the feature you're asking about [here](https://github.com/daattali/shinyjs/issues/118)

**Comment by daattali** [comment]
@floriandeboissieu I decided to add back the `asis` functionality FYI , so any function that takes an ID can take `asis=TRUE` and then it won't be namespaced automatically

**Comment by floriandeboissieu** [comment]
Many thanks for your time, I hadn't got the time to try again, but it seems all good to me!
Cheers
