### ISSUE TITLE
Hidden plots rendered

### ISSUE THREAD

**Issue by HLeviel** [daattali/shinyjs#169]
Using shinyjs 1.0 with shiny 1.1.0 in a flexdashboard 0.5.1 makes plots in hidden tabs to be rendered.

[test.txt](https://github.com/daattali/shinyjs/files/2100199/test.txt)

Tabset  {.tabset .tabset-fade}
-------------------------------------
### Input
```{r Inputs, echo=FALSE}
useShinyjs(rmd=TRUE)
textInput("Input", "Input:")
observeEvent(input$Input, {})
```

### Plot 1
```{r, echo=FALSE}
renderPlot({warning("Chart1")})
```

### Plot 2
```{r, echo=FALSE}
renderPlot({warning("Chart2")})
```

**Comment by daattali** [comment]
I don't understand what you're trying to do and what the problem is. Can you please rephrase and show exactly what the issue is?

**Comment by daattali** [comment]
Can you provide a reproducible example? The code you provided doesn't actually show any inputs or any plots. I need to be able to replicate exactly what you're seeing

**Comment by HLeviel** [comment]
Yes, you can read the warning : the correct behaviour is the warning only appears when each tab is clicked. On my setup, the code provided shows both warning at loading.

**Comment by daattali** [comment]
I'm not sure why that's happening, what rstudio are you using? The warnings don't show up on load for me on my local machine, they only show up one by one when I click on a tab. I have the same shiny and flexdashboard versions (but using the latest shinyjs from github)

**Comment by HLeviel** [comment]
I'm using RStudio 1.0.153, I will try using github version and keep you  updated

**Comment by daattali** [comment]
I'd be very surprised if an updated shinyjs version fixes the problem,
because I can't think of what would cause that issue. Maybe the rstudio
version, because it is a bit old, but I still don't understand what causes
it. Unfortunately I cannot replicate. Please see if you can replicate the
problem on other machines

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by HLeviel** [comment]
You were right, I still have issue with R 3.5, RStudio 1.1.453 and dev version of shinyjs, with either rstudio viewer or Chrome  66.0.3359.181. 
But If I use Firefox 60.0.1 (64 bits) it is OK

**Comment by daattali** [comment]
Very strange. Please let me know if you can replicate it with other people or on other machines

**Comment by HLeviel** [comment]
I replicated on 2 other setups :
- first one stand alone RStudio / win 7, same as mine, with exact same behavior 
- second one with R Studio Server / Linux, it happens not at first load but sometimes after editing and saving Rmd file. I could not figure out how to systematically reproduce.
And it's only with Chrome, it never happened with Firefox.

**Comment by daattali** [comment]
Is this still an issue?

**Comment by HLeviel** [comment]
Hi Dean,
I'm not currently working on the project that showed the issue...
Guessing you can close it if I'm the only one concerned.
Thanks!
Hubert

Le mar. 30 oct. 2018 à 06:06, Dean Attali <notifications@github.com> a
écrit :

**Comment by daattali** [comment]
If it becomes an issue again and you can help me reproduce it, feel free to re-open
