### ISSUE TITLE
formalize or document shinyjs.collapse

### ISSUE THREAD

**Issue by r2evans** [daattali/shinyjs#172]
You initially recommended code in https://stackoverflow.com/a/32110791/3358272 that allows for the programmatic collapsing of a `box()`. Do you think it would be useful enough to either add as a formal `shinyjs::collapse` or at least add to a list of Tips/Tricks with ShinyJS?

**Comment by daattali** [comment]
This is too specific of a usecase to warrant adding a function for it in shinyjs. But adding it to the list of tricks n tips is a good idea. Feel free to make a pull request there.  Thanks!
