### ISSUE TITLE
Bug in _getElements when using selector & ns()

### ISSUE THREAD

**Issue by avsdev-cw** [daattali/shinyjs#175]
This bug occurs when trying to use the "selector" parameter of shinyjs::hide when you are also using shiny namespaces.  The id parameter is always set using the namespace internally by shinyjs (even though the id parameter defaults to NULL) and due to the order of the if/else the selector parameter effectively gets ignored.  I believe the precedence order of of _getElements needs to be changed using the below patch.

A better/future fix might be to check the id parameter of hide() because using NULL is a valid parameter:
``` 
library(shiny)
serv <- function(input, output, session) {
   print(session$ns(NULL)) # prints: [1] "test_ns"
}
runApp(shinyApp(fluidPage(), function(input, output){ callModule(serv, "test_ns"); }))
```
I'm assuming this also applies to hideElement(), show(), showElement(), toggle() and toggleElement() since they all use the _getElements method

quick patch:
```
diff --git a/inst/srcjs/shinyjs-default-funcs.js b/inst/srcjs/shinyjs-default-funcs.js
index 36b7f4a..c43713e 100644
--- a/inst/srcjs/shinyjs-default-funcs.js
+++ b/inst/srcjs/shinyjs-default-funcs.js
@@ -64,10 +64,10 @@ shinyjs = function() {
     var $els = null;
     if (params.elements !== null && typeof params.elements !== "undefined") {
       $els = params.elements;
-    } else if (params.id !== null && typeof params.id !== "undefined") {
-      $els = _jqid(params.id);
     } else if (params.selector !== null && typeof params.selector !== "undefined") {
       $els = $(params.selector);
+    } else if (params.id !== null && typeof params.id !== "undefined") {
+      $els = _jqid(params.id);
     }
     if ($els === null || $els === undefined || $els.length == 0) {
       shinyjs.debugMessage("shinyjs: Could not find DOM element using these parameters:");

```

**Comment by avsdev-cw** [comment]
NOTE: bug is probably a regression introduced by https://github.com/floriandeboissieu/shinyjs/commit/5c1b4503497bafc13aa26741d82d7ba863747076

**Comment by daattali** [comment]
The commit you mention is in a different repository - is this bug present in this shinyjs or if the forked copy?

If it's present here, please include a reproducible example

**Comment by daattali** [comment]
Can you please include a full reproducible example that showcases the issue? Thanks :)

**Comment by avsdev-cw** [comment]
Ah, commit 8627e85f61f3535ea85f9409c7a86246daa2a203 fixes the issue in master.

Any ETA on when a new stable will be available on CRAN?

**Comment by daattali** [comment]
Before end of year

**Comment by avsdev-cw** [comment]
Great, Thanks!

**Comment by daattali** [comment]
@avsdev-cw it looks like I was a bit off... by more than a year! In case you wanted to know, I just submitted the new version to CRAN so it should be on CRAN next week.
