### ISSUE TITLE
Show/Hide does not work with certain outputId names

### ISSUE THREAD

**Issue by jeffkeller87** [daattali/shinyjs#176]
Shiny supports fairly arbitrary `outputId` names as far as I can tell e.g., ``output$`a weird - name` ``. But `shinyjs::show` and `shinyjs::hide` doesn't like this unless I use syntactically valid names e.g., via `make.names()`.

I suspect there's a character escaping issue/omission somewhere on the JS side.

**Comment by daattali** [comment]
This happened because jquery selectors do not accept spaces (as well as some other special characters). Should be fixed now.
