### ISSUE TITLE
disabled doesn't work on actionLink

### ISSUE THREAD

**Issue by ericricky** [daattali/shinyjs#179]
`disabled(actionLink(...))` isn't working for me. Here is a working example:

```R
library(shiny)
library(shinyjs)

server = shinyServer(function(input, output) {
  output$out = renderText(input$link)
})

ui = shinyUI(fluidPage(
  useShinyjs(),
  disabled(actionLink("link", "Disabled Action Link")),
  uiOutput("out")
))

shinyApp(ui, server)
```

Haven't looked at the source code but is there an easy fix?

**Comment by daattali** [comment]
Enabling/disabling only applies to inputs, not to links. This is not just shinyjs-specific, this is standard web practice - it doesn't really make sense to talk about links as being disabled.
