### ISSUE TITLE
Passing arguments from R to JavaScript

### ISSUE THREAD

**Issue by afflorezr** [daattali/shinyjs#18]
Hello Dean,

Thank you so much for this package, it has helped me a lot. 
But right now im having trouble linking the JS function with my json data. The function creates a highchart plot and it receives the data in json format. When I link the data with the function out of the ui.R or server.R it works perfectly, but it isnt a reactive object, because it isnt inside of ui.R or server.R, I believe that with the shinyjs package is possible to make this happen.

I have tried with the following code:

require(shiny)
require(shinyjs)
library(rHighcharts)
library(rCharts)
require(RJSONIO)
#require(lubridate)
require(plyr)

f1<-"shinyjs.SegmPlot=function (datos) {
                datos = shinyjs.getParams(datos);
                $('#segmentos').highcharts({
                chart: {
                type: 'column'
                },
                credits: {
                enabled: false
                },
                title: {
                text: 'Indicadores de Retención'
                },
                exporting: {
                enabled: false
                },
                tooltip: {
                pointFormat: '<b>{point.y:,.2f}</b>%'
                },
                subtitle: {
                text: 'Por Segmentos:'
                },
                xAxis: {
                categories: ['Continuidad','Reactivación 1i','Reactivación 2i'],
                crosshair: false
                },
                yAxis: {
                min: 0,
                title: {
                text: 'Proporción'
                }
                },
                plotOptions: {
                column: {
                pointPadding: 0.2,
                borderWidth: 0
                }
                },
                series:datos
                });
                }"

runApp(shinyApp(
  ui = bootstrapPage(
    useShinyjs(),
    extendShinyjs(text = f1),

    mainPanel(
      div(js$SegmPlot(
        RJSONIO::toJSON(list(
          list(name='Diamante',color='#BDB8B4',data=c(90,70,30)),
          list(name='Esmeralda',color='#00a480',data=c(85,65,27)),
          list(name='Zafiro',color='#7573A6',data=c(83,63,26)),
          list(name='Rubí',color='#E0115F',data=c(75,35,18))
          
        ))
      )
    ))
  ),
  server = function(input,output,session) {

  }
))

But with no succes, I dont know if extendShinyjs function goes inside the ui.R or the server.R and neither how I should call the function f1 so it can create the highchart plot.

Thank you for your attention and Ill be looking forward for your answer.

**Comment by daattali** [comment]
Responded via email
