### ISSUE TITLE
reset() does nor reset shinyWidgets elements

### ISSUE THREAD

**Issue by robertoromor** [daattali/shinyjs#180]
I am trying to create a form and use a "ClearButton" to reset all my inputs once the user gets done filling a form. I tried using the function reset(), shinyjs::reset(), wrap the inputaddon into an exclusive div(id=) and nothng works.

I believe it is related to the special syntax of the shinyWidget but I cant figure it out. 

Thanks in advance!

  library(shinyjs)
  runApp(shinyApp(
    ui = fluidPage(
      useShinyjs(),
      
        div(id = "form",
            textInput("name1", "NormalTextInput", "Dean"),
            div(id="id1", textInputAddon(inputId = "name", value="test", label = "ShinyWidgetInput", placeholder = "Username", addon = icon("at"))),
            numericInput("age", "Age", 26),
            selectInput("letter", "Favourite letter", LETTERS)
        ),
      
      actionButton("resetName", "Reset name"),
      actionButton("resetAll", "Reset all")
    ),
    server = function(input, output, session) {
      observeEvent(input$resetName, {
        reset("name")
        reset("name1")
        shinyjs::reset("id1")
      })
      observeEvent(input$resetAll, {
        reset("form")
      })
    }
  ))

**Comment by daattali** [comment]
Currently only native shiny inputs are supported, because each input type needs to be explicitly dealt with with custom code. I've briefly thought about this in the past, whether it's a good idea to start supporting all sorts of other third party inputs. My worry is that they are not as stable and consistent as shiny inputs and it'll just become a nightmare to maintain. Since 99%+ of inputs are shiny inputs, I'm hesitant to add that work to my long list of things I need to support, but I may consider it later.

**Comment by robertoromor** [comment]
Makes sense,  Thanks for the quick answer and the package!

**Comment by daattali** [comment]
I'll keep it open until the next time I devote some thought to this.

**Comment by DrumSergio** [comment]
I was going to open another issue but I think it fits here. I cannot disable/enable a button of shinyWidgets for my app.

**Comment by daattali** [comment]
@DrumSergio It looks like the shinyWidgets download button can't get disabled from what I tried to do manually (changing the DOM to add a "disabled" class or adding a "disabled" attribute). Maybe the creator of shinyWidgets can let you know what DOM changes need to happen to disable that button, if any

**Comment by daattali** [comment]
I've added support for many shinyWidgets inputs, but textInputAddon specifically is one of the few inputs that are not able to be supported yet.

**Comment by daattali** [comment]
Actually, `textInputAddon()` is deprecated. The newer alternative, `textInputIcon()`, does work with `reset()`
