### ISSUE TITLE
Selectize Group Module - Selectize input Height

### ISSUE THREAD

**Issue by Gaurav9112** [daattali/shinyjs#181]
Hi I want to lower the height of Selectize Inputs in selectize Group Module

Default settings are:
.selectize-group .selectize-input {
    height: 72px;
    overflow-y: scroll;
}

I want to adjust height to 15px 

How can I do it ?

**Comment by daattali** [comment]
This sounds like purely a CSS question, not a shinyjs bug or feature request. I suggest asking on stackoverflow for help with "how do I do X" type questions
