### ISSUE TITLE
disabled doesn't work for selectInput

### ISSUE THREAD

**Issue by nbbn** [daattali/shinyjs#186]
Hi,
let's have shiny app:
```
library(shiny)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  shinyjs::disabled(selectInput(
          inputId = 'asdadasd',
          label = 'test',
          choices = c('asd','asda','asdadasd'),
          selected = c('asd','asda','asdadasd'),
          multiple = TRUE,
          selectize = FALSE
        ))
)

server <- function(input, output) {
}

shinyApp(ui = ui, server = server)
```
What I get is:
![image](https://user-images.githubusercontent.com/7264317/60262867-86e82300-98df-11e9-9ecd-e134eb30f227.png)

I would like to have disabled select element, not div (this disabled=disabled is not propagated to children of element).
I report it as bug, because I believe hat it should be smartly applied to div and children (e.g. select) or to select at least.

**Comment by daattali** [comment]
Fixed
