### ISSUE TITLE
Document requirements / examples of using extendShinyjs within a package

### ISSUE THREAD

**Issue by lianos** [daattali/shinyjs#188]
I think it might be helpful to note in the man page of `extendShinyjs` (or its vignette) that if you want to use the `extendShinyjs` within a package (PkgA) and not have *shinyjs* in its `Depends` or run from a script that explicitly calls `library("shinyjs")`, then PkgA needs to explicitly import the `js` object from the *shinyjs* package.

I am happy to provide PR with a first cut of documentation within the man page or the vignette, if you like. I'm sorry of this is already documented somewhere and I missed it.

## Background

Apologies for the long winded background below, but I think it will help make more sense to the description above if it's not clear enough yet.

I have a shiny package ([*multiGSEA.shiny*](https://github.com/lianos/multiGSEA.shiny)) that provides (hopefully) re-usable modules as well as a shiny app that uses all of the modules in order to facilitate exploratory data analysis.

One particular module in the *multiGSEA.shiny* package uses the `extendShinyjs` functionality and has been working well for me for a long while when running that application in a manner that forces a call to `library(shinyjs)` (via the [`multiGSEA.shiny::explore()`](https://github.com/lianos/multiGSEA.shiny/blob/40e38e7ff4f4b4f0ee564d93196a6b9c4cd617b7/R/shiny-utils.R#L23) function).

I am now developing a new package and want to leverage some of the modules in *multiGSEA.shiny* to build a shiny gadget within it while trying to be a bit cleaner/more formal with the my calls to "library" and what is listed in Depends of the new package. In the new package, I am only importing the server and UI functions of the modules from *multiGSEA.shiny* that I want to use in the new package.

As a result, there is never a call to `library(shinyjs)` in the codepath to launch my new gadget which uses the modules from *multiGSEA.shiny*, and I was getting errors along the lines of `js object can not be found` when invoking a module from within *multiGSEA.shiny* (specifically [from this line](https://github.com/lianos/multiGSEA.shiny/blob/40e38e7ff4f4b4f0ee564d93196a6b9c4cd617b7/R/shiny-module-geneSetContrastView.R#L103)).

It took me some time to realize (what is obvious in retrospect) that the `js` environment is within *shinyjs*'s namespace, and including `importFrom(shinyjs,js)` in *multiGSEA.shiny*'s NAMESPACE resolves the issue, enabling the modules within the *multiGSEA.shiny* to be re-used by other packages, without loading the *shinyjs* package into the workspace.

**Comment by daattali** [comment]
Thanks for the very detailed report and the initiative to add this yourself.

I'm not sure how much adding that kind of documentation would help. When developing a package, especially an exported function, it's already highly recommended to explicitly namespace every object. If someone forget to namespace `js`, I doubt that they will think to look at the `extendShinyjs` documentation and find a sentence that reminds them that `js` needs to be namespaced.

I'm sorry for the time you lost on tracking down that issue nonetheless

**Comment by lianos** [comment]
Perhaps you're right.

For me it wasn't a matter of forgetting to namespace `js`, but rather where I should have been looking for `js` to begin with until it smacked me in the face.

For some reason I had first imagined some "rube goldberg machine"-like setup wondering if the `extendShinyjs` function was materializing this object upon its first invocation somewhere and then was stuck in that rabbit hole for a bit.

Of course that doesn't make much sense ... perhaps I'll just chalk it up to it being my first day back from vacation and my brain still being stuck on the beach.

Thanks this package, btw, it really comes in handy when you need it.

**Comment by daattali** [comment]
Let's go with the beach explanation :) Thanks for understanding!
