### ISSUE TITLE
shinyjs::reset does not reset `choices` of `selectizeInput`

### ISSUE THREAD

**Issue by RemkoDuursma** [daattali/shinyjs#191]
`reset` resets the selection of `selectizeInput` without problems, but the available choices are not reset (if these are updated with `updateSelectizeInput`) - I could not find in the documentation (or elsewhere) whether this is expected behaviour, a feature, or perhaps a bug.

A workaround is not really a problem (calling an extra `updateSelectizeinput`), but it would be cleaner (and perhaps faster?) to do everything with a single `reset()`.

Example:

```
library(shiny)
library(shinyjs)

ui <- fluidPage(
  
  useShinyjs(),
  
  div(id = "resettable",
    selectizeInput("sel1", "Selection 1", choices = letters, selected = "a")
  ),
    actionButton("btn_restrict", "Less choices"),
    actionButton("btn_reset", "Reset", icon = icon("refresh"))
  
  
)

server <- function(input, output, session) {

  session$onSessionEnded(stopApp)
  
  observeEvent(input$btn_restrict, {
    
    updateSelectizeInput(session, "sel1", choices = letters[1:2])

  })
  
  observeEvent(input$btn_reset, {
   
    shinyjs::reset("resettable")
    # or in this case, reset("sel1"), same result
    
  })
  
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Thanks for the report. The current behaviour is the expected behaviour - it should reset the **value**, not all the properties of the input. I'm closing this issue as it's out of scope for `reset`
