### ISSUE TITLE
Error in show when using PL locale

### ISSUE THREAD

**Issue by jcubic** [daattali/shinyjs#192]
I think I've found errror in shinyjs I have code like this:

shinyjs::show(self$ns("buttonPrevious")) or shinyjs::hide

and it give error in JSON:

```javascript
{"custom":{"shinyjs-show":{"id":"EfficacyAnalysisComponent1_buttonNext","anim":false,"animType":"slide","time":0,5,"selector":null}}}
```

the problem is `,"time":0,5` 0,5 is probably because of Polish locale that use comma as float separator (instead of dot in EN).

**Comment by daattali** [comment]
Does this also break when using a simple show example, not with modules?
Please provide a complete code sample as minimal as possible. Thanks for
the report

**Comment by jcubic** [comment]
Those are not modules, self$ns is not part of shiny module. Will try to recreate with minimal code.

**Comment by jcubic** [comment]
I don't know what happened with my application because simple example works fine. Just to be sure I've set `Sys.setlocale("LC_ALL","pl_PL.UTF-8")` and it send proper JSON `"time":0.5` will investigate why I've got the error maybe it's not related to locale, for now I've used `time = 0` since I don't need animation at all.

**Comment by daattali** [comment]
I'll close the issue for now, please open again if you have a reprex
