### ISSUE TITLE
Odd behaviour when starting with a disabled downloadButton

### ISSUE THREAD

**Issue by TonyLadson** [daattali/shinyjs#194]
Hi,

If I start with downloadButton disabled, and then enable it, the filename function in downloadHandler doesn't seem to work properly.  The suggested filename is NA.

Here's a simple example (code plus screenshot)
<img width="906" alt="Save File 2019-09-24 11-56-01" src="https://user-images.githubusercontent.com/1966541/65475291-63268000-dec2-11e9-8d80-0f1d60f79603.png">

The work around is not to use disabled in the ui but instead disable the button in the server and then enable it as required.

```
library(shiny)
library(shinyjs)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  checkboxInput('save_data', 'Enable Save'),
  disabled(downloadButton("downloadData", "Download"))
)

server <- function(input, output) {
 
  data <- mtcars
  
  observeEvent(input$save_data, {
     if(input$save_data) {enable("downloadData")
     } else {
       disable("downloadData")
     }
  })
  
  output$downloadData <- downloadHandler(
    filename = function() {
      paste("data-", Sys.Date(), ".csv", sep="")
    },
    content = function(file) {
      write.csv(data, file)
    }
  )
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Have you tried opening the app in a real browser? (Chrome, Safari, Firefox, etc)

The code works fine for me in a real browser. Inside RStudio it doesn't work, but even without the disabled feature it doesn't work inside RStudio for me. The RStudio browser is known to have a lot of bugs, that's not something that shinyjs can do. If this problem persists in a proper browser, let me know. I cannot reproduce.

**Comment by TonyLadson** [comment]
I think you are right.  Seems to work ok in Safari.  Thank you
