### ISSUE TITLE
Disabling downloadButton inside a module requires `ns`

### ISSUE THREAD

**Issue by ahmohamed** [daattali/shinyjs#196]
Thanks for an awesome package.
As far as my understanding goes, using `shinyjs::disable(id)` does not require wrapping with `ns` for namespaced elements. Apparently, `dowloadButton` is an exception. Minimal example below.

```r
library(shiny)
library(shinythemes)

modui <- function(id) {
  ns <- NS(id)
  div(
    downloadButton(ns('dlmod'), "Download-module"),
    downloadButton(ns('dlmod_ns'), "Download-module-ns"), 
    actionButton(ns('actnmod'), "Action-module")
  )
}
mod <- function(input, output, session) {
  ns <- session$ns
  output$dlmod <- downloadHandler(
    "any", function(file) {print("dlmod");disable("dlmod")} # NOT disabled
  )
  output$dlmod_ns <- downloadHandler(
    "any", function(file) {print("dlmod_ns");disable(ns("dlmod_ns"))} # disabled
  )
  observeEvent(input$actnmod, {print("actnmod");disable("actnmod")}) # disabled
}
shinyApp(
  ui = fluidPage(theme=shinytheme("united"),
    useShinyjs(), modui("mod"), 
    downloadButton('dl', "Download", status="primary"),
    actionButton('actn', "Action")
  ),
  server = function(input, output, session) {
    callModule(mod, "mod")
    output$dl <- downloadHandler("any", function(file) {print("dl");disable("dl")}) # disabled
    observeEvent(input$actn, {print("actn");disable("actn");}) # disabled
  }
)
```

Cheers.

**Comment by ahmohamed** [comment]
I did some modifications to the code above, and it seems that the problem was not the `downloadButton`, but the context from which `shinyjs` was called (i.e the `content` function of `downloadHandler`). This is because the following works:

```r
# Disables both `actnmod` and `dlmod`
observeEvent(input$actnmod, {print("actnmod");disable("actnmod"); disable("dlmod")})
```

**Comment by daattali** [comment]
Can you please try to post a **minimal** clear example, the code provided does show the problem you mention but there's too much going on there to be able to easily pinpoint the issue. Only the absolute minimum simplest code to reproduce the problem is needed.

**Comment by daattali** [comment]
Ah, you already responded that you noticed the disable actually does work. This is a good demonstration of why trying to reproduce the simplest code is a good idea :)

The reason it doesn't work in your original example is because within the download handler, shiny is actually using a different R session, it doesn't have access to the same module namespace. Inside a download handler you're not in the same session. It's not a shinyjs issue, it's just the way download handlers work.
