### ISSUE TITLE
extendShinyjs does not return values?

### ISSUE THREAD

**Issue by slfan2013** [daattali/shinyjs#197]
in my ui, I tried to created a javascript function to return some value like 

`extendShinyjs(text = 'shinyjs.test=function(){return(1)}', functions = c("test")),`

and run this function in the server with 

` print(js$test())`

The R console shows the result is `NULL`. Why the result is not `1`?

**Comment by daattali** [comment]
javascript functions cannot return values to shiny, they can only be used to run javascript expressions. If you want to pass a value from javascript to shiny, see here: https://github.com/daattali/advanced-shiny#message-javascript-r
