### ISSUE TITLE
`click()` doesn't work with download buttons

### ISSUE THREAD

**Issue by daattali** [daattali/shinyjs#198]
`click()` works with regular buttons but not with download buttons.

Example:

```
library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  downloadButton("go")
)

server <- function(input, output, session) {
  observe({
    shinyjs::click("go")
  })
  output$go <- downloadHandler(
    filename = "file",
    content = function(file) {
      print("test")
    }
  )
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Fixed with https://github.com/daattali/shinyjs/commit/cc9678c98462d36e4725cbcd56bc658a07e725a7

**Comment by stevepowell99** [comment]
is there any way to make click() work with selectors rather than ids? I have an element which I would like to click on but it doesn't have an id.

**Comment by federiva** [comment]
Maybe you can try something like?:
```r
runjs("$(<'yourselector'>).click()")
```
Just try to be sure that you're not running that on multiple elements, just to avoid unexpected click events somewhere else in the DOM

**Comment by daattali** [comment]
The function is meant to be used for action buttons, which always have IDs, and it's kind of a strange thought to click on multiple buttons simultaneously. Therefore it can only be used with an ID. You can use the suggestion above to make your own version of click with some minimal javascript.

**Comment by stevepowell99** [comment]
tx, this works. The use case is sorting a DT datatable by a specific column, where there are no IDs but I can identify the correct column with a selector, and DT doesn't provide easy sorting via proxy, so this is really useful.
