### ISSUE TITLE
Issue installation recent version 

### ISSUE THREAD

**Issue by maruca8** [daattali/shinyjs#199]
Dear Dean,

I am currently trying to download the version 1.1 of your package.
This is my code and the ouput:

```{r}
install.packages('shinyjs')
```
Output:

 There is a binary version available but the source version is later:
        binary source needs_compilation
shinyjs    1.0    1.1             FALSE

installing the source package ‘shinyjs’

trying URL 'https://cran.rstudio.com/src/contrib/shinyjs_1.1.tar.gz'
Content type 'application/x-gzip' length 957877 bytes (935 KB)
downloaded 935 KB

Warning: invalid package 'C:\Users\Maria'
Warning: invalid package 'Castellanos\AppData\Local\Temp\RtmpecvzNA/downloaded_packages/shinyjs_1.1.tar.gz'
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘shinyjs’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Maria Castellanos\AppData\Local\Temp\RtmpecvzNA\downloaded_packages’
> ```
Error: attempt to use zero-length variable name
> 
> ```{r}
Error: attempt to use zero-length variable name

Second code (I downloaded the tar.gz file to my computer):

> install.packages("shinyjs_1.1.tar.gz", repos = NULL, type = "source")

Output:
Installing package into ‘C:/Users/Maria Castellanos/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'shinyjs' ...
** package 'shinyjs' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Fatal error: cannot open file 'C:\Users\Maria': No such file or directory

ERROR: lazy loading failed for package 'shinyjs'
* removing 'C:/Users/Maria Castellanos/Documents/R/win-library/3.6/shinyjs'
Warning in install.packages :
  installation of package ‘shinyjs_1.1.tar.gz’ had non-zero exit status
> ```
Error: attempt to use zero-length variable name

```{r}
install.packages("shinyjs_1.1.tar.gz", repos = NULL, type = "source")
```

Any help will be appreciated, thanks!

**Comment by daattali** [comment]
Are you able to install other packages? This doesn't seem like a shinyjs issue, it seems like like a problem with the R package installer. Try completely removing the package from your system and reinstalling. It looks like maybe it's having problems because your user name ("Maria Castellanos") has a space in it, because look at the first warning: "Warning: invalid package 'C:\Users\Maria'"

**Comment by maruca8** [comment]
Dear Dean, you were absolutely correct. it was the space between my name and last name the cause of it. I have downloaded many R packages without problem, but for this one, it was an issue.  I created a new user account with no space and now it works. Thank you for your quick and good response!
