### ISSUE TITLE
runjs() removes backslashes from the code

### ISSUE THREAD

**Issue by drzamich** [daattali/shinyjs#200]
In my Shiny application I want to take the dataframe and send it to the front-end by firstly parsing it to JSON and then using `runjs()` to send the JSON string to the UI. The problem arises when some field in the dataframe contains double quotes (`"`). The `jsonlite::toJSON()` adds backslashes to escape them but `runjs()` seems to be removing the backslashes under the hood.

Consider the following code snippet:
```R
df <- data.frame(employee = c('John "Doe"'))
df_json <- jsonlite::toJSON(df) # [{"employee":"John \"Doe\""}]
cmd <- paste0("console.log('",df_json,"');")
shinyjs::runjs(cmd)
```

when I run it, this is what is displayed in the console
```JSON
[{"employee":"John "Doe""}]
```
as you can see, this is not a valid JSON, as there is too many double quotes.

**Comment by drzamich** [comment]
I looked into the source code and noticed that `runjs()` uses JS's `eval()` under the hood which is responsible for removing backslashes.

```js
eval("console.log('[{\"employee\":\"John \\\"Doe\\\"\"}]');") //  [{"employee":"John "Doe""}]
```

**Comment by daattali** [comment]
I'm not sure if what you're seeing is wrong. My initial reaction is that it's correct. You might want to print out `JSON.stringify(x)`?

**Comment by daattali** [comment]
@drzamich if you don't have any more thoughts on this, I'd like to close the issue
