### ISSUE TITLE
typescript?

### ISSUE THREAD

**Issue by rl627** [daattali/shinyjs#208]
Hi very new to utilizing javascript in shiny but I saw a cool typescript library that I would use in Shiny.  Is this possible with shinyjs?

**Comment by daattali** [comment]
I'm presonally not too familiar with typescript, I don't know how to use it with R/shiny. Have you seen typescript used in shiny?

**Comment by rl627** [comment]
Not really. just curious to see if anyone was looking into this. Thanks for the help!
