### ISSUE TITLE
sound on server - the "Attali" solution

### ISSUE THREAD

**Issue by abbatidanilo** [daattali/shinyjs#209]
Hello Dean,
Since the scope of my web-app is to analyze a set of entry files, some of the calculus take a long time to execute. For this reason, beside a visual acknowledge, I prefer to implement a "sound when complete" mechanism.
In stand-alone mode is easy: I simply used play(x = ding) in the server.R and the library(audio).
But on the shinyapps.io server I though the right way was to use the:
```tags$audio(src = "wavs/ding.wav", type = "audio/wav", autoplay = NA)``` inside the ui.R but invain.
Then I tried with your solution (the Attali solution) as suggested in: 
https://community.rstudio.com/t/unexpected-tags-audio-behavior/67636/5?u=abbati 
but with great disappoint does not work either:
I deployed in shinyapps.io also added the library(V8) as suggested by the server after a first deployment.
No way. The server does not play any sound.
Here we are an extract of my implementation:
On ui.R
```library(shinyjs)
useShinyjs(),
                extendShinyjs(text = 'shinyjs.ding = function() {var snd = new Audio("./www/ding.ogg"); snd.play(); }'),  
```
on server.R
```
if (Sys.info()["sysname"] == "Windows") {play(x = bell)} else {js$ding()}} 
```
Nothing
probably I missed something...

**Comment by daattali** [comment]
I never tried doing this on shinyappsio. There are certain things (not just with shinyjs) that don't work there. I don't know when I'll have time to look into this issue, but it is possible that it simply doesn't work in shinyappsio.

**Comment by abbatidanilo** [comment]
No problem Dan,
thank you anyway for your attention and most of all for your precious packages.
