### ISSUE TITLE
Failing to implement shinyjs in observers

### ISSUE THREAD

**Issue by mbacou** [daattali/shinyjs#21]
Dean,
I'm testing shinyjs on a Shiny dashboard I'm developing at http://tools.harvestchoice.org/cell5m/ (github https://github.com/harvestchoice/hc-shiny/tree/master/cell5m), but I haven't been able to successfully implement any method from within `shinyServer()`. 

I would like to use shinyjs to control the visibility of 3 user panels on top of the main leaflet map, and do need a little more fine-grained control over their behavior.

As an example, I would expect the hidden white panel `panelInd` (on pic below) to toggle with `line 102` in `server.R`, 

```
shinyjs::show(id="panelInd", anim=T)
```

but that currently fails with:

```
Warning: Unhandled error in observer: attempt to apply non-function
observeEvent(input$selectCat)
```

I've tried any number of shinyjs methods, e.g. at `line 85`, etc. with no success either.

```
onclick("selectCat", shinyjs::toggle(id="panelInd", anim=T))
```

fails with,

```
Error in .getReactiveEnvironment()$currentContext() : 
  Operation not allowed without an active reactive context. (You tried to do something that can only be done from inside a reactive expression or observer.)
```
Hitting a roadblock, and hoping you might be able to catch my mistakes. Thanks!

![image](https://cloud.githubusercontent.com/assets/260325/8686247/a6f18808-2a52-11e5-9e71-0fea402a1a89.png)

**Comment by daattali** [comment]
I can't think of the reason off the top of my head, you're the first person to run into such issues.  I would need to run the app myself to debug.  Is there any way for me to run it locally, I see that downloading hcapi3 package is not possible and even without that I was running into errors.  Can you try to replicate the problem with less other packages being around so that I could more easily debug?

**Comment by mbacou** [comment]
Dean, yes that was my next step. Will try to replicate with a more minimal example, and add packages one by one then.

**Comment by daattali** [comment]
That would be best. But if you could just get it to a state where I can test it myself, even if it's not minimal, I'd work with that

**Comment by daattali** [comment]
@mbacou I just made some internal changes to shinyjs and there's a chance that this fixes your problem. Could you try downloading the latest version from github (v0.0.8.2) and see if your code works now? Thanks

**Comment by mbacou** [comment]
@daattali great, thanks! I'll try over the weekend and will report back. Haven't had a chance to debug the earlier errors, too little time on my end.

**Comment by daattali** [comment]
Hi @mbacou have you had a chance to try to see if the problem persists or is there a way for me to reproduce it?

**Comment by mbacou** [comment]
@daattali, problem seems fixed, thanks! I yes just had a chance to test again (sorry I'm not working on this app full time -- yet).
