### ISSUE TITLE
href in shinyjs::info

### ISSUE THREAD

**Issue by Baboon61** [daattali/shinyjs#212]
I'm trying to set up an href in a `shinyjs::info` pop up.
Including an `HTML` function inside `shinyjs::info` did the trick when I run the app inside a Rstudio window but failed when I run the app in a browser, outputting what's inside the HTML function as plain text.
I've made a StackOverflow question with an example but we are stuck. Thanks a lot

https://stackoverflow.com/questions/63111980/display-hyperlink-into-shinyinfo

**Comment by daattali** [comment]
I answered on the stackoverflow. This is not supposed to work and I'm surprised that in RStudio it works. JavaScript's alert function is meant to only accept and show plain text.
