### ISSUE TITLE
Error: shinyjs: could not find the Shiny session object. 

### ISSUE THREAD

**Issue by RicardoFCJ** [daattali/shinyjs#214]
This is a reproducible example:
```
library(shiny);library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  hide(actionButton("hide","LABEL")),
  actionButton("show","LABEL")
)

server <- function(input, output, session) {
  observeEvent(input$show,{
    show("hide")
  })
  observeEvent(input$hide,{
    hide("hide")
  })
}

shinyApp(ui, server)
```

The app doesn't even start with the error:
_Error: shinyjs: could not find the Shiny session object. This usually happens when a shinyjs function is called from a context that wasn't set up by a Shiny session._

I'm using Ubuntu 20 64 bits, R version 3.6.3.

**Comment by daattali** [comment]
You're using  a hide function  in the UI. The hide function is a server
function.
