### ISSUE TITLE
`toggle()` is not effecitve in module.

### ISSUE THREAD

**Issue by earnaud** [daattali/shinyjs#215]
I am using `shinyjs::toggle()` with condition to toggle a `div` element by its ns-ed id. 
It worked last week, does not anymore today (dev's life). 
I have some questions/things to report:

**How shall the id be noted?**

I use toggle in a module, and I want to toggle a div with an id set as `NS("PI")` in the UI. Shall it be noted `session$ns("PI")` or just `"PI"` in `toggle` ? 
This question is never told in shiny* packages doc when handling ids.

**asJSON message**

Two things are happening while expecting a single toggling:

- `toggle()` does not work anymore (div keeps being shown, even if the condition properly switches from FALSE to TRUE as expected)

- I get the following message upon executing `toggle()`: 
```
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.
``` 

It is used by {shiny} when communicating a `session$sendCustomMessage` as far as I know. 

I am working on a reprex.

**Comment by earnaud** [comment]
NOTA: I updated my packages yesterday, and this bug occurred then. It surely came with the last release (2020-09-09 if I am right).

**Comment by daattali** [comment]
I'll be able to respond/fix after you submit a reprex. Just like other native shiny functions, namespace is required only in the UI but not in the server

**Comment by daattali** [comment]
Here's a minimal reprex and proof that toggle works in a module. If you believe there's an issue, please only open an issue after being able to provide a reprex and exact details.

```
test_UI <- function(id) {
  ns <- NS(id)
  tagList(
    actionButton(ns("btn"), "Click me"),
    textInput(ns("text"), "Text")
  )
}

test <- function(input, output, session) {
  observeEvent(input$btn, {
    shinyjs::toggle("text")
  })
}

library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  test_UI("test")
)

server <- function(input, output, session) {
  callModule(test, "test")
}

shinyApp(ui, server)
```

**Comment by earnaud** [comment]
Well, it is - again - in a "complexe" shiny app. I indeed tried a simple reprex and didn't reproduce the issue. The thing is the bug occurs while executing the `toggle()` function, so I naively reported it here. But it might be due to a shiny internal.

**Comment by daattali** [comment]
I'm closing this issue for now - if you're able to find a reproducible example that shows the issue in shinyjs, please do let me know!
