### ISSUE TITLE
When disabled() a Panel, downloadbutton not affected

### ISSUE THREAD

**Issue by CheeseSlicer** [daattali/shinyjs#223]
When using `shinyjs::disabled()` with a Panel, it disables textinputs and actionbuttons like expected. However, downloadButtons get ignored and stay enabled. If you put the downloadButton solely into `disabled` though, it works like in originally posted by @daattali in https://github.com/daattali/shinyjs/issues/132#issuecomment-46767938.

MWE:
```
library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  shinyjs::disabled(
    wellPanel(
      id = "test_panel",
      downloadButton("testdw", "testdw"),
      actionButton("testab","testab"),
      textInput("testtext","testtext")
    )
    )
)

server <- function(input, output, session) {
  output$test <- downloadHandler(
    filename = "test.csv",
    content = function(con) {
      write.csv(mtcars, con)
    }
  )
}

shinyApp(ui, server)
```
![grafik](https://user-images.githubusercontent.com/18083323/99509488-1b946a80-2986-11eb-9b8d-3a6d57b91f12.png)

**Comment by daattali** [comment]
Thanks, should be fixed now
