### ISSUE TITLE
Error: 'JS' is not an exported object from 'namespace:V8'

### ISSUE THREAD

**Issue by sanchez5674** [daattali/shinyjs#24]
Hi, 

I got the latest dev version of shinyjs and tried to run you demo piece of code

```
library(shiny)
library(shinyjs)

jsCode <- "shinyjs.pageCol = function(params){$('body').css('background', params);}"

runApp(shinyApp(
  ui = fluidPage(
    useShinyjs(),
    extendShinyjs(text = jsCode),
    selectInput("col", "Colour:",
                c("white", "yellow", "red", "blue", "purple"))
  ),
  server = function(input, output) {
    observeEvent(input$col, {
      js$pageCol(input$col)
    })
  }
))
```

But got the error above. Any ideas? 

Carlos

**Comment by sanchez5674** [comment]
Hi, 

BTW, I'm running locally so it has nothing to do with the shinyapps.io problem people have reported in the past. Importing V8 did not seem to have any effect. 

Carlos

**Comment by daattali** [comment]
That's very strange, I just ran it myself and it's fine.  Can you send me your `sessionInfo()`?  I know it works on windows 7 and on ubuntu 14, if it's a different OS it might be hard for me to test

**Comment by sanchez5674** [comment]
Hi, 

This is the sessionInfo()

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinyjs_0.0.8.3 shiny_0.12.1   

loaded via a namespace (and not attached):
 [1] R6_2.1.0         Rcpp_0.12.0      V8_0.5           curl_0.5        
 [5] digest_0.6.8     htmltools_0.2.6  httpuv_1.3.2     jsonlite_0.9.16 
 [9] mime_0.3         rstudio_0.98.507 rstudioapi_0.2   tools_3.1.2     
[13] xtable_1.7-4   
```
Hopefully you see something obvious. 

Thanks!

**Comment by daattali** [comment]
Ah, I see now. You're using `V8` version 0.5, and `shinyjs` requires version `0.6` or higher (the DESCRIPTION file says that).  Update V8, that should fix it :) Please try it and close this issue if that works

**Comment by sanchez5674** [comment]
Hi Dean, 

That solved the problem. My bad. 

Thanks!
