### ISSUE TITLE
Clarify license in README and website

### ISSUE THREAD

**Issue by davidwales** [daattali/shinyjs#240]
Thanks for a great package!

Looking at CRAN, it appears that this package is MIT licensed.
However, this was not clear to me from either the website or the GitHub README.

It would be great if this were easier to find. 😄

**Comment by daattali** [comment]
It used to be a commercial license but I changed it to MIT. Is there anywhere in the README or on the website or anywhere else that still says "commercial" or gives any indication it's not free to use?

**Comment by davidwales** [comment]
I was confused because there is nowhere on the website or README that mentions the MIT license.
Also, the license file just has your name and the copyright year. (I understand that's the format required by CRAN).

The way that copyright works, unless something is explicitly licensed, it's not free to use.
I can use it because I found the MIT license on CRAN. But if I hadn't thought to check CRAN, I would not have felt able to use it.

**Comment by daattali** [comment]
This is the standard convention for R packages: the license is provided in the DESCRIPTION file. Every R package follows this format. I try to keep the README concise so I'd rather not put raised non essential information in it.

**Comment by davidwales** [comment]
Thanks. I'm not particular familiar with R packaging conventions.

Would you consider at least adding the line: `License: MIT + file LICENSE` to the README or the website?
This would help people like myself who don't know to look in the DESCRIPTION file. (Or even `License: See DESCRIPTION`)

**Comment by daattali** [comment]
I really prefer not to add more information or badges to the readme. Most R packages are MIT, and don't explicitly say so because it's required to write it in the DESCRIPTION.

I do think the LICENSE file should say "MIT" in it, and I actually advocated for that in the past, because that would make the license file a standalone. But unfortunately CRAN does not want to support that, so this is where we are

**Comment by davidwales** [comment]
I'll close this issue then. Thanks again for a great package. :)
