### ISSUE TITLE
Allow to remove the events

### ISSUE THREAD

**Issue by jcubic** [daattali/shinyjs#244]
This is like a major flaw in this library I don't see a way to remove the event that was added using shinyjs.

Is there any way to remove everything that is attached to an element? Including mutation observer helpers.

**Comment by daattali** [comment]
That's a valid concern. I'll think about how to best add a mechanism to remove events.

**Comment by daattali** [comment]
I added a function `removeEvent`

**Comment by jcubic** [comment]
Awesome, thanks.
