### ISSUE TITLE
disabled does not carry through to fileInput

### ISSUE THREAD

**Issue by bhogan-mitre** [daattali/shinyjs#249]
Similar to #223, the `disabled` function does not get carried through to the nested button.  The input itself is disabled, so nothing happens when you click it.  But it's a bit deceptive to users to have a clickable button that is disabled.

```
library(shiny)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  shinyjs::disabled(
    fileInput("testup", "testupload")
  )
)

server <- function(input, output, session) {}

shinyApp(ui, server)
```

<img width="341" alt="Screen Shot 2022-05-04 at 2 46 44 AM" src="https://user-images.githubusercontent.com/32336739/166634454-bd850205-a4bb-400f-a443-edb105349965.png">

Do you think it would work to cast the net a little wider and add `span[btn]` to the set of elements that are checked when enabling/disabling?
https://github.com/daattali/shinyjs/blob/master/inst/srcjs/shinyjs-default-funcs.js#L238

**Comment by daattali** [comment]
It took a little bit more to fix this, but it should work now. Thanks for the report.

**Comment by bhogan-mitre** [comment]
Great, thanks for the fix!
