### ISSUE TITLE
hidden() doesn't work on a tagList() containing an htmlDependency()

### ISSUE THREAD

**Issue by cpsievert** [daattali/shinyjs#252]
First reported in https://github.com/rstudio/shiny/issues/3670

Here's a minimal reprex

```r
library(htmltools)

shinyjs::hidden(
  tagList(
    div(),
    htmlDependency(name = "foo", src = "", version = "1.0")
  )
)
```

**Comment by daattali** [comment]
Thanks for the report!

**Comment by daattali** [comment]
Fixed in both `hidden()` and `disabled()`. Please install latest github version and confirm it works in your usecase @gitdemont

**Comment by gitdemont** [comment]
It perfectly works !  THANKS 👍
