### ISSUE TITLE
Include help or an example for users of index.html

### ISSUE THREAD

**Issue by AlunHewinson** [daattali/shinyjs#31]
Some shiny users use index.html in place of ui.R.  I've just found the shinyjs package and am keen to test it in working apps, but I don't see how to the equivalent of `useShinyjs()` in the header of an index.html file.

I'll work it out eventually, but making it explicit in the help/examples for other users of index.html would be a welcome addition to the documentation.

**Comment by daattali** [comment]
Hi Alun, that's a great point, but I actually never used index.html so I'm not quite sure what the solution is. I'm hoping it's very easy to integrate `shinyjs` into HTML-only apps, but I really have no clue what's involved until I'll get more familiar with that style of writing apps.

I just spent a lot of time this week on a new version of shinyjs and will now shift my focus to a few other things (including my school :smile: ) so I don't think I'll be looking into this soon.  If you're familiar with index.html and do figure out how to use shinyjs, please do report back so it can be communicated with everyone else.

Thanks!

**Comment by AlunHewinson** [comment]
Just a note to anyone else reading this: I'm working on this after a conversation with daattali, but I'll be on vacation in one week for two weeks.  If there's no more news on this thread in the next few days, expect something in the middle of September.

**Comment by daattali** [comment]
Thanks @AlunHewinson , enjoy your vacation. I'm curious to see if you find a nice clean solution at some point

**Comment by AlunHewinson** [comment]
So I've got something working with a basic app

In the same directory as `index.html`, I have a directory called `shared2`, with subdirectories containing javascript and css file.  This is the sort of thing anyone using index.html should have, and will not be covered here.

Within the `<head>` section of the `index.html` I have
```
<script type="text/javascript" src="shared2/js/shinyjs-default-funcs.js"></script>
<script type="text/javascript" src="shared2/js/input_binding_colour.js"></script>
<script type="text/javascript" src="shared2/js/shinyjs.js"></script>
```
Those files have, of course, been placed in the relevant folder.  They come from the shinyjs package.

In the same directory as server.R is a file called global.R.  That file consists of
```
library(shiny)
library(shinyjs)
useShinyjs()
```

That seems to be enough to make the ordinary functions in the shinyjs package available to server.R.  I've tested it with `info()` and an alert appears as expected.

I don't have a solution for extendShinyjs, but I think it's possible to recreate its behaviour.  Since you'd need to write the javascript part into a .js file (not forgetting the `addCustomMessageHandler` which binds what R sends to the js function), it might be best just to manually make an R function to take the parameters and send it through `session$sendCustomMessage()`.
Perhaps a general solution would be to have a new function in this package, perhaps called `extendUserjs()` or something, that looks in a particular javascript file, gets the functions and their arguments, and makes an R function with the same name and arguments.

But all that is a little beyond what I've time and inclination to do right now.  The above solution is a bit bodgy but it gets the inbuilt functions working.  I'll post a quick example of the index and server code, but bear in mind that it won't work without copying some files into the right place as referenced in `<head>`

**Comment by AlunHewinson** [comment]
This might not be the bare minimum; I have a pretty long and complex html file I've tried to pare down for this example, but there might be some rubbish left in :)

index.html:

```
<!DOCTYPE html>
<html lang="en">
	<head>

	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <title> Page title </title>

	    <!-- JQuery -->
	    <script src="shared2/jquery.js" type="text/javascript"></script>

	    <!-- shiny JS -->
	    <script src="shared2/shiny.js" type="text/javascript"></script>

	    <link href="shared2/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
	    <script src="shared2/bootstrap/js/bootstrap.min.js"></script>
	    <script src="shared2/bootstrap/shim/html5shiv.min.js"></script>
	    <script src="shared2/bootstrap/shim/respond.min.js"></script>
	    
	    <link href="shared2/selectize/css/selectize.bootstrap3.css" rel="stylesheet" />

	    <script src="shared2/selectize/js/selectize.min.js"></script>

	    <!-- Shiny Core CSS -->
	    <link href="shared2/shiny.css" rel="stylesheet" />

	    <!-- Slider -->
	    <link href="shared2/ionrangeslider/css/normalize.css" rel="stylesheet" />
	    <link href="shared2/ionrangeslider/css/ion.rangeSlider.css" rel="stylesheet" />
	    <link href="shared2/ionrangeslider/css/ion.rangeSlider.skinShiny.css" rel="stylesheet" />
	    <script src="shared2/ionrangeslider/js/ion.rangeSlider.min.js"></script>

	    <script src="shared2/js/json2-min.js"></script>

	    <!-- shinyJS -->
	    <script type="text/javascript" src="shared2/js/shinyjs-default-funcs.js"></script>
	    <script type="text/javascript" src="shared2/js/input_binding_colour.js"></script>
	    <script type="text/javascript" src="shared2/js/shinyjs.js"></script>
	</head>

	<body>
		<div class="container-fluid">
		  	<div class="row">
		    	<div class="col-sm-4">
		      		<form class="well">
		        		<div class="form-group shiny-input-container">
		          			<label class="control-label" for="obs">Number of observations:</label>
		          			<input class="js-range-slider" id="obs" data-min="10" data-max="500" data-from="100" data-step="1" data-grid="true" data-grid-num="10" data-grid-snap="false" data-prettify-separator="," data-keyboard="true" data-keyboard-step="0.204081632653061" data-drag-interval="true" data-data-type="number"/>
		        		</div>
		      		</form>
		    	</div>
		    	<div class="col-sm-8">
		      		<div id="distPlot" class="shiny-plot-output" style="width: 100% ; height: 400px"></div>
		    	</div>
		  	</div>
		</div> 
	</body>
</html>
```

server.R:

```
library(shiny)
library(shinyjs)

server <- function(input, output) {
  
  reactObs <- reactive({
    info('hello')
    input$obs
  })
  
  output$distPlot <- renderPlot({
    hist(rnorm(reactObs()), col = 'darkgray', border = 'white')
  })
}
```

And global.R
```
library(shiny)
library(shinyjs)
useShinyjs()
```

File structure:
```
global.R
server.R
www/
 |- index.html
 |- shared2/
     |- js/
     |- css/
        ... and so on
```
The exact location of the js and css files is flexible; just make sure you reference them with the right paths from where index.html is stored, and that you do so in the right order: shiny.js comes before anything that uses shiny bindings, etc.  The above is pretty untidy but it works.

**Comment by daattali** [comment]
Thank you @AlunHewinson ! I've never looked at how to make shiny apps with custom HTML, so I'll look at the basics soon and then at your comments

**Comment by daattali** [comment]
@AlunHewinson what's in your "shinyjs.js"?  Does it hold all the `Shiny.addCustomMessageHandler(...)` calls? I can't seem to find a way that will dynamicaly create all those calls

**Comment by daattali** [comment]
Hey @AlunHewinson I think I found a way to support shinyjs in html file apps that requires very minimal set up from on the user's part. I used a bit of your ideas, thanks for making me do this.

I'd appreciate if you could try it out and let me know if it works for you and if you find it easy. I updated the README https://github.com/daattali/shinyjs

You basically just need to do three things:

- create a `global.R` file in the same directory as your server.R, and add the following line to the file:
        `shiny::addResourcePath("shinyjs", system.file("srcjs", package = "shinyjs"))`

- in the index.html file you need to load a special JavaScript file named `shinyjs/inject.js`. You do this by adding the following line to the HTML's <head> tag:
        `<script src="shinyjs/inject.js"></script>`

- in your server function (the shinyServer function) you need to call useShinyjs(html = TRUE)

Now shinyjs should work. You can even use `extendShinyjs()` without a problem, both using text and using script.  Let me know if you find it works well

**Comment by AlunHewinson** [comment]
This shinyjs.js file does contain the addCustomMessageHandler calls, yes.  Hmmm, I can see that this might be something that I put together before my vacation. #confusion

I'll take a look at your later suggestion today...

**Comment by daattali** [comment]
I wanted to avoid the user having to make his own files or providing a file
that will have to be updated every time I add new functions. I think the
current solution is the simplest to use

**Comment by AlunHewinson** [comment]
I forgot to post the update yesterday after I tried your suggestion here.  It works!  Brilliant work, and thank you for your time.  Your method is a lot neater than my rambling sprawl of code.

**Comment by daattali** [comment]
Awesome. Thank you for bringing up this issue and doing the initial work. I'm really happy to know all shiny apps can now use shinyjs, and it's nice to also know how to use index.html now :)
