### ISSUE TITLE
Similar to onclick, is it possible to add other on... functions to handle keyboard/mouse events?

### ISSUE THREAD

**Issue by doubletang** [daattali/shinyjs#34]
Like onhover, ondblclick, onmousemove, onkeydown/up. I think this would be a great extension to shiny.

**Comment by daattali** [comment]
I'm not sure how easy it'd be to implement a generic version of this. I'm really busy these days but I'll look into this when I have some time.

**Comment by daattali** [comment]
Hi @doubletang 
I added this functionality, can you please let me know if this works for you? You can do something like

```
  shiny::shinyApp(
    ui = shiny::fluidPage(
      useShinyjs(),
      textInput("text", "text")
    ),
    server = function(input, output) {
      onevent("mousemove", "text", cat("move"))
    }
  )
```

You won't have access to the data of the event (if it's a mouse event, you won't know where the mouse is and if it's a keyboard event, you won't know what key was pressed) -- for that you would need to use your own javascript. But this does work as a more generic method of `onclick`.

Hope this helps

**Comment by doubletang** [comment]
Great! It works very well. Thanks a lot!

**Comment by daattali** [comment]
Cool. I'll submit to CRAN next week probably
