### ISSUE TITLE
Right Side of Double Ended sliderInput Does Not Reset

### ISSUE THREAD

**Issue by phillc73** [daattali/shinyjs#37]
Using the reset function will only reset the left hand side of a double ended sliderInput. Any changes to the right hand side of the slider will not be reset.

I've tested with both the CRAN version of shinyjs and also the latest dev version from here on GitHub. The issue is present in both.

Sample code:

```R
library(shiny)
shinyApp(
  ui = fluidPage(
    shinyjs::useShinyjs(),
    div(id = "myApp",
        sliderInput("dailyDistance", label = h5("Slippery Slider"), min = 5, max = 50, value = c(5, 50), step = 1),
        actionButton("reset", "Reset form")
    )
  ),
  
  server = function(input, output) {
    observeEvent(input$reset, {
      shinyjs::reset("myApp")
    })    
  }
)
```
Tested browser is Chromium Version 41.0.2272.118 Built on 8.0, running on Debian 8.0 (64-bit)

**Comment by daattali** [comment]
Thank you @phillc73 , fixed now
