### ISSUE TITLE
extendshiny function parameter not working

### ISSUE THREAD

**Issue by debsush** [daattali/shinyjs#47]
Hi,

I have installed shinyjs 0.2.5.  I wanted to use extend shiny functionality using functions parameter since I am unable to install V8 package.  However, I get the following errors when I use

extendShinyjs(functions = "pageCol")

ERROR: shinyjs: V8 package is required to use `extendShinyjs`. Please install it with `install.packages("V8")`.
If you cannot successfully installV8 on your machine, you need to use the `functions` argument.
 
ERROR: shinyjs: Either `script` or `text` need to be provided. 

Wonder where did I go wrong

Regards

**Comment by daattali** [comment]
As the error message tells you, you still need to provide either `text` or `script`, because you need to somehow tell shinyjs what the actual JS code for your function is.  Look at the examples section of `?extendShinyjs`, it says 

```
    # If you do not have `V8` package installed, you will need to add another
    # argument to the `extendShinyjs()` function:
    # extendShinyjs(text = jsCode, functions = c("pageCol"))
```


It should work if you add the extra argument

**Comment by debsush** [comment]
Thank you. It works like a charm!!!
