### ISSUE TITLE
show/hide should always trigger shown/hidden events

### ISSUE THREAD

**Issue by jcheng5** [daattali/shinyjs#48]
https://github.com/daattali/shinyjs/blob/ca84b71cc2feda1be2cfe739142209997e1e29dc/inst/srcjs/shinyjs-default-funcs.js#L166-L173

Whenever an element is shown/hidden, Shiny wants to know about it. This allows Shiny to automatically suspend/resume outputs when the target element is hidden/shown. So maybe something more like:

```javascript
$.map($els, function(el) {
  $(el).trigger(method == "show" ? "shown" : "hidden");
});
```

**Comment by daattali** [comment]
You're right, that was a silly oversight. Just left the continent so will
fix as soon as I can. Thanks Joe
