### ISSUE TITLE
enable and disable actionButton not working within a module

### ISSUE THREAD

**Issue by jianwang2014** [daattali/shinyjs#54]
I modified a module example to show that shinyjs disable and enable feature doesn't work within a module.  Following is a module called testModule.R.  actionButton go4 is the test for shinyjs.  Other buttons are for conditionalPanel test.  Basically none of them work in a module environment.  By the way, I also tested all of them without a module, all work just fine.

Thanks for your attention.

# Module ui function -------------------------------------------------
testUI <- function(id, label = "CSV file") {
  # Create a namespace function using the provided id
  ns <- NS(id)
  
  tagList(wellPanel(
    fileInput(ns("file"), label),
    checkboxInput(ns("heading"), "Has heading"),
    selectInput(ns("quote"), "Quote", c(
      "None" = "",
      "Double quote" = "\"",
      "Single quote" = "'"
    ))),
    conditionalPanel(!is.null(ns("file")),
      actionButton("go1", label="Go Button1", icon = NULL)
    ),
    selectizeInput(
      ns("mySelect"), "Test Select", choices = state.name,
      options = list(
        placeholder = "Please select an option below",
        onInitialize = I('function() { this.setValue(""); }')
      )
    ),
    conditionalPanel("input.ns('mySelect') == 'Alabama' ", actionButton(ns("go2"), "Go Button2")),
    conditionalPanel("ns('input.mySelect') != ''", actionButton(ns("go3"), "Go Button3")),
    actionButton(ns("go4"), "Go Button4"),
    dataTableOutput(ns("table"))
  )
}

# Module server function -----------------------------------------------
test <- function(input, output, session, stringsAsFactors) {
  
  ns <- session$ns
  
  # The selected file, if any
  userFile <- reactive({
    # If no file is selected, don't do anything
    validate(need(input$file, message = FALSE))
    input$file
  })
  
  # The user's data, parsed into a data frame
  dataframe <- reactive({
    read.csv(userFile()$datapath,
             header = input$heading,
             quote = input$quote,
             stringsAsFactors = stringsAsFactors)
  })
  
  observe({
    if(ns("mySelect") != "Alabama") {
      shinyjs::disable(id=ns("go4"))
      return(NULL)
    } else {
      shinyjs::enable(id=ns("go4"))
    }
  })
  
  # We can run observers in here if we want to
  observe({
    msg <- sprintf("File %s was uploaded using testModule.R", userFile()$name)
    cat(msg, "\n")
  })
  
  output$table <- renderDataTable(dataframe())
}

**Comment by daattali** [comment]
That seems like a complex example and I'm not even sure what I'm supposed to do in the app. You don't need to use `ns()` inside the shinyjs functions, that's probably why it's not working for you. Try just `shinyjs::disable("go4")` instead.  If you're still getting problems, please try to come up with a simpler app to show exactly where the problem is.

By the way, instead of using an if statement to enable/disable, you can use the `toggleState` function.

Here is an illustration that enabling/disabling a button based on a selectInput value does work

```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id){
  
  ns <- NS(id)
  
  tagList(
    "Selecting Alabama will enable the button",
    selectInput(ns("state"), NULL, c("California", "Alabama", "Washington")),
    actionButton(ns("btn"), "Button")
  )
}


moduleTest <- function(input, output, session) {
  observe({
    toggleState("btn", condition = (input$state == "Alabama"))
  })
}


ui <- fluidPage(
  useShinyjs(debug = TRUE), 
  moduleTestUI('test')
)
server <- function(input, output, session) {
  callModule(moduleTest, 'test')
}
shinyApp(ui = ui, server = server)
```

**Comment by daattali** [comment]
@jianwang2014 please do let me know if it works or if you still think there's a problem with shinyjs

**Comment by shrektan** [comment]
ha, it works for me.

**Comment by daattali** [comment]
@shrektan thanks for verifying. Unless told otherwise, I'll assume this isn't actually a bug and will submit the current version to CRAN in a few days if no issues are reported

**Comment by jianwang2014** [comment]
Hi Dean:
Thanks much for examining this.  You are right.  It works after I removed
the ns in server code.

I didn't get to reply you right away because I also tested shinyjs for
actionButton controlling selectInput and reset in conditionalPanel.  All
work great!

Your help is greatly appreciated.
-Jian


On Mon, Jan 18, 2016 at 8:42 PM, Dean Attali <notifications@github.com>
wrote:

> That seems like a complex example and I'm not even sure what I'm supposed
> to do in the app. You don't need to use ns() inside the shinyjs
> functions, that's probably why it's not working for you. Try just
> shinyjs::disable("go4") instead. If you're still getting problems, please
> try to come up with a simpler app to show exactly where the problem is.
>
> By the way, instead of using an if statement to enable/disable, you can
> use the toggleState function.
>
> Here is an illustration that enabling/disabling a button based on a
> selectInput value does work
>
> library(shiny)
> library(shinyjs)
>
> moduleTestUI <- function(id){
>
>   ns <- NS(id)
>
>   tagList(
>     "Selecting Alabama will enable the button",
>     selectInput(ns("state"), NULL, c("California", "Alabama", "Washington")),
>     actionButton(ns("btn"), "Button")
>   )
> }
>
>
> moduleTest <- function(input, output, session) {
>   observe({
>     toggleState("btn", condition = (input$state == "Alabama"))
>   })
> }
>
>
> ui <- fluidPage(
>   useShinyjs(debug = TRUE),
>   moduleTestUI('test')
> )
> server <- function(input, output, session) {
>   callModule(moduleTest, 'test')
> }
> shinyApp(ui = ui, server = server)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daattali/shinyjs/issues/54#issuecomment-172702428>.
>



-- 
*-Jian Wang*

**Comment by daattali** [comment]
Thank you for your generous donation!

**Comment by DarioBoh** [comment]
This code should be pretty close to the working example but it uses `htmlOutput` and is not working for me. I posted it on SO but it has been a few days without any answers, thus I wonder if it might be a bug.

```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id, label='ui1'){
  ns <- NS(id)
     shinyUI(fluidPage(
       useShinyjs(debug = TRUE),
       actionButton(ns("btn"), "Submit", class='btn-primary')
     ))
}

moduleTest <- function(input, output, session) {
  observe({
    toggleState("btn", condition = F)
  })
}

ui <- htmlOutput("page")

server <- function(input, output,session) {
  output$page <- renderUI({
    ui1Output('test')
  })
  callModule(ui1,'test')
}

shinyApp(ui = ui, server = server)
```

**Comment by DarioBoh** [comment]
Based on your working example, I thought this was gonna work as well but is not. I posted the question on SO but it has been a few days without any answers, thus I wonder if there might be any issues linked with using `htmlOutput` in the `ui`
```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id, label='ui1'){
  ns <- NS(id)
     shinyUI(fluidPage(
       useShinyjs(debug = TRUE),
       actionButton(ns("btn"), "Submit", class='btn-primary')
     ))
}

moduleTest <- function(input, output, session) {
  observe({
    toggleState("btn", condition = F)
  })
}

ui <- htmlOutput("page")

server <- function(input, output,session) {
  output$page <- renderUI({
    moduleTestUI('ui1')
  })
  callModule(moduleTest,'test')
}

shinyApp(ui = ui, server = server)



```

**Comment by DarioBoh** [comment]
Based on your working example, I thought this was gonna work as well but it did not. I posted the question on SO but it has been a few days without any answers, thus I wonder if there might be any issues linked with using `htmlOutput` in the `ui`
```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id, label='ui1'){
  ns <- NS(id)
  shinyUI(fluidPage(
    useShinyjs(debug = TRUE),
    actionButton(ns("btn"), "Submit", class='btn-primary')
  ))
}

moduleTest <- function(input, output, session) {
  observe({
    toggleState("btn", condition = F)
  })
}

ui <- htmlOutput("page")

server <- function(input, output,session) {
  output$page <- renderUI({
    moduleTestUI('ui1')
  })
  callModule(moduleTest,'ui1')
}

shinyApp(ui = ui, server = server)



```

**Comment by daattali** [comment]
@DarioBoh using htmlOutput is not a problem,  I've used shinyjs inside modules with that before. But the way you're using it looks a bit awkwaRd  (like,  shouldn't shinyUI (fluidPage ()) go in the ui variable, and inside of that you should make a call to htmlOutput?)

Imy working on a lot of things at the moment and don't have the bandwidth to look into this but try refactoring your code a bit to make it more standard,  I think it will work then.  Sorry I can't be more help right now

**Comment by DarioBoh** [comment]
@daattali thanks for replying so fast 👍  
From my (very limited) understanding of what `fluidPage` does, I believe what you are saying is not a must. In my original app I am loading different pages in the `ui`, and not all of them are necessarily gonna be `fluidPage` layouts. Moreover, the layout comes out fine and the module is called properly. It's just `toggleState()` that does not seem to run.

**Comment by daattali** [comment]
@DarioBoh 

It looks like there are two problems with your code.

First problem: the `useShinyjs()` needs to happen when the page loads, not dynamically afterwards, if you want it to start working right away. So all I did was remove your call to useShinyjs and change the `ui <- ...` line to this:

    ui <- tagList(useShinyjs(), htmlOutput("page"))

Secondly, there's a slight timing issue going on with shiny: the `toggleState` function is being called before the element exists on the page yet. If you'll add another button to the UI `actionButton(ns("toggle"), "Toggle")` and add to the server `observeEvent(input$toggle, toggleState("btn"))` then you'll see that the toggling does work.  Alternatively, to get the toggleState function to work in your code upon initilization, what you can do as a dirty hacky solution is to wrap it in a `shinyjs::delay()` which will force its execution only after other javascript functions get called and the element will now have time to get created. `delay(0, toggleState("btn", condition = F))`

So to reiterate: the problem is not with using shinyjs inside a `htmlOutput`, that part works fine, it's just a javascript timing issue because the element is not created yet

**Comment by DarioBoh** [comment]
Thanks, I didn't know the location for calling `useShinyjs` would have made a difference because I misunderstood this part of the `useShinyjs` documentation:

> Description
> 
> This function must be called from a Shiny app's UI in order for all other shinyjs functions to work.
> You can call useShinyjs() from anywhere inside the UI.
> 
> Value
> Scripts that shinyjs requires that are automatically inserted to the app's `<head>` tag.
> 

And I thought the library was gonna load first from the head no matter what.

I fixed the code according to the "hacky" solution you suggested, but still cannot make it work. I tried with higher delays, and with adding the additional button too (2nd solution). None of them worked for me.

```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id, label='ui1'){
  ns <- NS(id)
     shinyUI(fluidPage(
       actionButton(ns("btn"), "Submit", class='btn-primary')
     ))
}

moduleTest <- function(input, output, session) {
    observe({
    delay(0, toggleState("btn", condition = F))
  })
}

ui <- tagList(useShinyjs(), htmlOutput("page"))

server <- function(input, output,session) {
  output$page <- renderUI({
    moduleTestUI('ui1')
  })
  callModule(moduleTest,'ui1')
}

shinyApp(ui = ui, server = server)

```

**Comment by daattali** [comment]
The library will still load even if you load it dynamically, but then it will only load after the page gets created, which is fine if you don't need to use it until then, but kind of weird. Better to just load it up in the beginning.

Your code that you just pasted does work for me. The button is disabled. Maybe try updating your shinyjs and shiny packages? This is the other solution I suggested, which also works when I run it:

```
library(shiny)
library(shinyjs)

moduleTestUI <- function(id, label='ui1'){
  ns <- NS(id)
  shinyUI(fluidPage(
    actionButton(ns("btn"), "Submit", class='btn-primary'),
    actionButton(ns("toggle"), "Toggle")
  ))
}

moduleTest <- function(input, output, session) {
  observeEvent(input$toggle, {
    toggleState("btn")
  })
}

ui <- tagList(useShinyjs(), htmlOutput("page"))

server <- function(input, output,session) {
  output$page <- renderUI({
    moduleTestUI('ui1')
  })
  callModule(moduleTest,'ui1')
}

shinyApp(ui = ui, server = server)
```

**Comment by DarioBoh** [comment]
Still not working, I have tried both scripts, reinstalled shiny and shinyjs (even if it was updated already) and updated R.

This is my session
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggvis_0.4.2  shinyjs_0.6  shiny_0.13.2
```
Thanks for your time, I'll ask somebody else to replicate and see if anyone have the same issue.

**Comment by daattali** [comment]
Very strange. I tried both on windows and on ubuntu. I don't have access to a mac os, but I would be very surprised if it's a general issue with mac, so yes it'd be nice if you could find someone who replicates :)

**Comment by DarioBoh** [comment]
@daattali your second example works, my explanation was probably confusing but I wanted the button to start as disabled. Thus the condition to be invalidate should be `is.null(input$toggle)`
```
 observeEvent(is.null(input$toggle), {
    toggleState("btn")
  })
```
I am still not able to have my first example working but I was planning to add another input element to observe as a condition anyway, thus the solution fits perfectly.

Thanks!

**Comment by daattali** [comment]
If you want a button to start as disabled, then try wrapping it inside
"shinyjs::disabled()". You can also do something like "toggleState("btn",
condition = (input$toggle %% 2 == 0))" or mod 2 == 1

---
http://deanattali.com
