### ISSUE TITLE
Look into writing/using a different JavaScript parser to remove V8 dependency

### ISSUE THREAD

**Issue by daattali** [daattali/shinyjs#57]
After speaking with Joe at the shiny devcon, he agreed that using `V8` only as a parser is overkill and I should try to write my own parser.  It's not a simple job, but I'll leave it here as a potential TODO.

All I want is a way to parse the provided JavaScript file/text, and extract all the `shinyjs.foo` names from it, and it'd also be nice if it validated the javascript

**Comment by daattali** [comment]
More notes:

Th reason I want to get rid of V8 as a dependency is because
- it doesn't cleanly install on all OS (it does on most OS that matter, but I'm just being OCD
- it requires system packages to be installed, which isn't *hard* per se, but it is a small point of friction. It'd be nice to use something that can be easily and smoothly installed in R without needing to install something else on the machine.

The main goal of the parser is
- to tell me what are all the keys inside the `shinyjs` object
- to validate the JS code (this isn't mandatory, but would be a nice feature that V8 does provide).

I could easily write a VERY hacky pseudo-pseudo-parser with a regex that would just look for stuff like `shinyjs.something = function` but that of course would be pretty bad. It'd be annoying to make sure it supports all kinds of ways to define shinyjs functions such as `shinyjs['foo'] = function()` or even `var funcname = "foo"; shinyjs[funcname] = function()`. I don't want to do this half-ass "parser".

So the best solution would be to either write my own parser (hard!) or find a simple JS parser that I can easily port and include here (much easier!)

I found a single-file C++ JS interpreter called [tiny-js](https://github.com/gfwilliams/tiny-js) which I think would work perfectly. @hrbrmstr has [an example](https://github.com/hrbrmstr/jasmine) of how to create an API to a simple c++ program which could be very similar to this.

**Comment by gfwilliams** [comment]
Hi - I just wanted to add that TinyJS isn't desperately standards-compliant, and might not be ideal for this. 42-tinyjs is a lot better I believe, or I have been working on Espruino which much much better (although it's not a single file any more!).

**Comment by daattali** [comment]
@gfwilliams thanks for your input, but unless TinyJS is completely broken, it should be enough. All I need is a way to read some JS code and know what all the keys inside a specific object are.  Simple enough, let me know if you think TinyJS wouldn't work for that for some reason.  I like how small it is and that it's just one file which makes it very easy to integrate

**Comment by hrbrmstr** [comment]
Now the Twitter q has context! :-)

**Comment by hrbrmstr** [comment]
Try: <https://github.com/hrbrmstr/tinyjs>

It's _super_ -alpha. No error checking at all. But it does the following:

```library(tinyjs)

init()

exec("var a=10;")
get("a")
## [1] "10"

exec("var b={this:'that', or:4, the:['ot', 'he', 'r']};")
get("b")
## [1] "{ \n  \"this\" : \"that\",\n  \"or\" : 4,\n  \"the\" : [\n\"ot\",\n\"he\",\n\"r\"\n  ]\n}"```

**Comment by hrbrmstr** [comment]
I need to wrap that the same way Jeroen did but I'm doing this between some things.

**Comment by daattali** [comment]
@hrbrmstr AWESOME :tada: 

It does work.  This makes me very happy, to know that soon I can remove the V8 dependency. 

A few comments:
- Are the files Script.cpp, TinyJS_Functions and TinyJS_MathFunctions needed?
- I see you're using `onAttach()`, doesn't that mean that you assume tinyjs will be attached with a library call? I tried using it with namespacing instead and it did work
- it's a bit of a weird interaction to call `js_eval()` and not save the result into any variable and have it just saved to a global variable. Is that what you meant by wrapping it/tlaking about `XPtr`?  If it's a lot of work to change this then no worries, it can stay like this.
- THANK YOU

I really don't expect you to do this right now or at all. Completely up to you!

**Comment by daattali** [comment]
After playing with it for a few more minutes, I found two big obstacles to using tinyjs:

- it errors out if a line does not end in a semicolon (`eval_js("a=5")`)
- it errors out when trying to retrieve the value of an object that contains functions. (`eval_js("a={}; a.b=7;a.c=function(){};"); js_get("a")`)

Maybe @gfwilliams is right and using [42tiny-js](https://github.com/gfwilliams/tiny-js/tree/42tiny-js) (a different branch with a much larger file) is better, if it handles these two things

**Comment by hrbrmstr** [comment]
anything is doable :-) I modeled it after the V8 interface but if you have
a desired "API", lemme know (just toss ideas into the `tinyjs` repo). I've
been doing this half-distracted today (giant meetings FTW) so some things
may be unnecessary. i'll be able to poke a bit later.

There are two diff ways to go with this pkg. Keep it truly simple (i.e. not
as complex as V8 and only support one active js context and only expose a
minimal API or replicate the V8 API fully so folks can just swap out  the
`library(V8)` call. Not sure which is better.

**Comment by hrbrmstr** [comment]
cool. i can take a look at that one. it doesn't seem like it'll be hard to
do that. the lack of a semicolon is JS think (I think V8 wld whine too) but
I'll poke at it.

**Comment by hrbrmstr** [comment]
a quick look indicates that I might just try to work around any issues in
the less-enhanced version. it does build on Windows, too (forgot to add
tests, but compile is a gd sign)

**Comment by daattali** [comment]
The lack of semicolon is not supposed to give a problem (V8 and any browser would happily accept a single statement `a=5`, I think tinyjs just isn't robust enough to accept it, that's why I suggested maybe seeing is 42tinyjs is better. But if you think it's not as useable, then I trust you).

**Comment by daattali** [comment]
I work on Windows, so don't worry about checking it on windows too much, I can be the tester for that!

**Comment by daattali** [comment]
@hrbrmstr just poking you see if you want to ever maybe come back to give this a try :)

**Comment by daattali** [comment]
@hrbrmstr do you think you might come back to finish this at some point?

**Comment by AnuragMohta** [comment]
Hey Dean,

Hope you are doing well !

The V8 dependency is causing issue on deploying shiny apps to RStudio Connect (although , not in all cases). Do you have any suggestions for us so that we can still use shinyjs without walking into the issue. Please let me know if you need any further details.

**Comment by daattali** [comment]
Are you unable to deploy an app that uses V8? That sounds like an issue with V8, have you tried submitting an issue on that package?

**Comment by daattali** [comment]
The V8 dependency has been removed recently 🎉
