### ISSUE TITLE
Problem with `toggleState` based on a datatable  `input$tableID_rows_selected` object in modularized Shiny app

### ISSUE THREAD

**Issue by thercast** [daattali/shinyjs#58]
I'm honestly not quite sure if this issue is caused by something in shinyjs or in the DT package itself, but here's my issue.  I'm creating an app in which the user will need to click on a row shown in a data table and press an action button to do something based on the selection.  I want the action button disabled until the user clicks on a row in the data table to minimize confusion.  Here's a simple Shiny app that works without a problem (without using modules):

### Normal version of app 

```
library(shiny)
library(DT)

ui <- fluidPage(
  shinyjs::useShinyjs(),
  fluidRow(
    h1("Demo app"),
    DT::dataTableOutput('mydata'),
    actionButton("mybutton", "Click me!"),
    verbatimTextOutput('selections')
  )
)

server <- function(input, output, session) {
  df <- iris[, 1:3]
  options(DT.options <- list(pageLength = 5))
  output$mydata <- DT::renderDataTable(df, server = FALSE, selection = 'single')
  output$selections <- renderPrint({
    list(
      last_clicked = input$mydata_row_last_clicked,
      row_selected = input$mydata_rows_selected
    )
  })
  observe({
    shinyjs::toggleState(id = "mybutton", condition = (length(input$mydata_rows_selected) > 0))
  })
  observeEvent(input$mybutton, {
    shinyjs::info("Hi there you clicked the button!")
  })
}

shinyApp(ui, server)
```
You'll see that the button is properly disabled until you select a row.  But in the modularized app version below, the button is still enabled when no row is selected in the table.  What's strange is the printed output of what row was selected is showing properly in both apps.  Any idea of how I can properly use this functionality in a modularized app?  I'm using shiny `0.13` from CRAN, shinyjs `0.2.5` from GitHub, and DT `0.1.45` from GitHub.

### Modularized version of app

```
library(shiny)
library(DT)

myappUI <- function(id) {
  ns <- NS(id)
  tagList(
    h1("Demo app"),
    DT::dataTableOutput(ns('mydata')),
    actionButton(ns("mybutton"), "Click me!"),
    verbatimTextOutput(ns('selections'))
  )
}

myapp <- function(input, output, session) {
  df <- iris[, 1:3]
  options(DT.options <- list(pageLength = 5))
  output$mydata <- DT::renderDataTable(df, server = FALSE, selection = 'single')
  output$selections <- renderPrint({
    list(
      last_clicked = input$mydata_row_last_clicked,
      row_selected = input$mydata_rows_selected
    )
  })
  
  observe({
    shinyjs::toggleState(id = "mybutton", condition = (length(input$mydata_rows_selected) > 0))
  })
  
  observeEvent(input$mybutton, {
    shinyjs::info("Hi there you clicked the button!")
  })
}


ui <- fluidPage(
  shinyjs::useShinyjs(),
  fluidRow(
    myappUI("first")
  )
)

server <- function(input, output, session) {
  callModule(myapp, "first")
}

shinyApp(ui, server)
```

@daattali Best of luck with your paper and thesis!

**Comment by daattali** [comment]
@thercast you're using a very old shinyjs version.  The Shiny modules feature wasn't out yet back then.  Version 0.4 of shinyjs (which is on CRAN already too) supports modules.  I just tried running this code locally and it worked fine.  Let me know after using a newer shinyjs version if it works.

Unfortunately any shiny apps that use modules HAS to update shinyjs to the newer version

**Comment by thercast** [comment]
:relieved: well that was embarrassing, I'm usually much better about checking for more up-to-date versions of shiny-related packages.  I've been using packrat with this app and lost track of how old the shinyjs version was.  Closing now!

**Comment by daattali** [comment]
It's not actually that old, I just looked and it's from 2015-12-14. So no need to feel bad :)  I just did a bunch of updates that results in two major versions just to get it ready for the conference
