### ISSUE TITLE
remove double quotation marks in message of info function

### ISSUE THREAD

**Issue by funnng** [daattali/shinyjs#59]
the info function will write the double quotation marks in the message,
remove it from the output of info function will make it more clear.
what you think?
![qq20160224-0](https://cloud.githubusercontent.com/assets/394134/13278407/423cb8a0-db0b-11e5-856f-863268e983c2.png)

**Comment by daattali** [comment]
Good idea, I never really paid attention to that.  I'll do this in a few weeks when I have some down time

**Comment by Yang-Tang** [comment]
Is it possible to support adding shiny html widgets like textInput, checkBox, or actionButton in the info page?

**Comment by daattali** [comment]
@Yang-Tang no, that's not possible.  It's not a "page", it's simply a dialog that can only show text, not an actual popup that can contain HTML
