### ISSUE TITLE
Can't select additional colours

### ISSUE THREAD

**Issue by pozelei** [daattali/shinyjs#64]
Hi,
really like the addin! But we got an issue here both on Mac and Windows. If we add a second colour (or more) we cannot select it with the mouse. We tried attaching shinyjs explicitly and tried both the current CRAN release and the Github version. My session info in the case of the Mac environment:

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_0.13.1

loaded via a namespace (and not attached):
 [1] R6_2.1.2        htmltools_0.3   tools_3.2.3     rstudioapi_0.5  Rcpp_0.12.3     jsonlite_0.9.19 digest_0.6.9   
 [8] xtable_1.8-2    httpuv_1.3.3    mime_0.4        miniUI_0.1.1    shinyjs_0.5.2

**Comment by daattali** [comment]
What do you mean you can't select it - when you move your cursor over the square with the number 2 and click, nothing happens?  What about when you start the colour picker with multiple boxes, for example type `colourPicker(3)`, it also doesn't work then?

Can you see open the app in your browser (by going to 127.0.0.0:<port> according to what RStudio tells you the port is), opening the javascript console, and see if there are any errors?

**Comment by pozelei** [comment]
Yes correct, nothing happens! Thats the same case for manually starting it with more than 1 colour. I'll try checking the Javascript console and report back.

**Comment by pozelei** [comment]
When opend in the browser (Firefox) no errors show up when I try to select the second or third (or....) colour (tried manually starting the addin as well).
The only thing that pops up right after I started the addin is:
![screenshot 2016-04-05 11 54 32](https://cloud.githubusercontent.com/assets/7760212/14278151/7a99a376-fb26-11e5-8c7e-a6acb84a55f7.png)

**Comment by daattali** [comment]
Ah, so there is an error! It can't load the javascript. It's trying to load shinyjs-funcs.js and it's failing for some reason. I'll try to see why that happens......

**Comment by daattali** [comment]
I'm guessing selecting colours from the second tab isn't working, and that in the third tab the loading image never disappears? Those are also things that require the javascript  file

**Comment by pozelei** [comment]
Yes thats correct!

**Comment by pozelei** [comment]
Is that a local bug? Usually I have no problems with JS applications within RStudio...

**Comment by daattali** [comment]
I tried installing shinyjs on a few different machines (all Windows) and it worked, so I'm not sure what's going on here....... I'll think about it.  But at least we know where the problem is.

**Comment by daattali** [comment]
Can you translate the first error message to me? And tell me the full name of the file that it's failing at? (shiny.m....)

**Comment by pozelei** [comment]
"The connection to ws: ..... was canceld during loading of the page."

Gotta go eat....be back in 30...

**Comment by daattali** [comment]
I just tried installing on a Linux server I have and it worked there too. Strange.

That sounds like an error with shiny for some reason. I wish I had access to your computer so that I could debug :)

Can you see if that same error about the socket being cancelled also happens when you run an empty shiny app?

```
library(shiny)

ui <- fluidPage(
  "hello"
)

server <- function(input, output, session) {
  
}

shinyApp(ui = ui, server = server)
```


If that works and you don't see the error in the console, can you try this one?

```
library(shiny)

jscode <- "shinyjs.init = function() { alert('hello!'); }"

ui <- fluidPage(
  shinyjs::useShinyjs(),
  shinyjs::extendShinyjs(text = jscode, functions = c()),
  "hello"
)

server <- function(input, output, session) {
  
}

shinyApp(ui = ui, server = server)
```

**Comment by pozelei** [comment]
Sorry! Im back now :)
The first example works without any errors. The second works and the message pops up but it also says that "Connection to ws://127.0.0.1:5196/websocket/ was canceld while loading of the page."

**Comment by pozelei** [comment]
I just tried Chrome as well. Here the error log is at least in english ;)

![screenshot 2016-04-05 14 45 40](https://cloud.githubusercontent.com/assets/7760212/14282113/3146b33c-fb3d-11e5-9851-9def63c45f9a.png)

I checked the path. shiny-funcs.js is just where it should be...

**Comment by pozelei** [comment]
Would'nt a work-around be to make shinyjs-funcs.js available by putting it in the www folder? Sorry if thats a stupid idea ;)

**Comment by pozelei** [comment]
Oh my...

just found out that the package V8 is needed. After installing it it worked... -.-

**Comment by daattali** [comment]
V8 is not a hard requirement. It's a suggested requirement, but this should work without it. 

I see now that if I don't have V8, I get the same error.  I'm not sure why having V8 makes a difference in whether the path works or not, but now we really nailed down where the problem is. Thank you so much for your patience and help!  I'll report back when I find a solution

**Comment by pozelei** [comment]
Ah right. When I found the paragraph on V8 I just tried it without reading in detail what it is about. As long as it works now I happy. Really useful tool ;) Looking forward to your fix anyhow...

**Comment by daattali** [comment]
@pozelei I think I fixed it. If you don't mind, could you try uninstalling V8 (by just removing the folder V8 from your library) and make sure the colour picker still works?

**Comment by pozelei** [comment]
Yep, I can confirm it works now without the help of V8! :) Thx!

**Comment by daattali** [comment]
Great, thank **you**!
