### ISSUE TITLE
onevent() and onclick() should work with groups too

### ISSUE THREAD

**Issue by adrfantini** [daattali/shinyjs#69]
onevent() and onclick() require a layerId input. However, in many cases one creates points, markers etc. setting only the group. It would be nice if one could pass the group instead of the Id.

Example use case:
using leaflet, I want the user to select N points on a map. Then, hovering over one of the points, which share a group but have unknown Ids, something should happen.

**Comment by daattali** [comment]
Sorry I'm not sure what you mean by "group" and "layerId".  Is this something to do with leaflet?  Right now `onevent()` and `onclick()` require an id, yes, so do you mean that you want to be able to specify a CSS selector, like you can do with the `hide()` function for example?  If that's what you mean then unfortunately I don't think I'll add that ability anytime soon, these two functions are complex and I can't think of a way to support that

**Comment by adrfantini** [comment]
I'm so sorry, I totally thought that groups were a feature of Shiny, while they only are a feature of Leaflet. My bad. It would still be nice if it was supported, but I realize it's a more specific case. Thanks again.

**Comment by daattali** [comment]
I'm going to close this issue , feel free to re-open if you find anything to add that is relevant to shinyjs. I prefer to stay away from adding any functionality that is specific to a certain package
