### ISSUE TITLE
Return cookie information?

### ISSUE THREAD

**Issue by iainmwallace** [daattali/shinyjs#70]
Hi,

Is it possible to use return details on a cookie using shinyjs? I have a cookie called 'UserCookieProfile' and I would like to return the attribute called 'PreferredName' from it.

I have come across a couple of questions about it, but am unclear on what a solution would look like. 

https://groups.google.com/forum/#!msg/shiny-discuss/nHFbL0K38k8/FndeYifoAwAJ
http://stackoverflow.com/questions/32353680/how-to-access-browser-session-cookies-from-within-shiny-app

thanks

Iain

**Comment by daattali** [comment]
I'm not sure how cookie information in shiny apps works.  This isn't really a shinyjs question, it's more of a shiny or JavaScript question.  I never looked into cookies in shiny apps, not sure how to access them. Sorry!

**Comment by iainmwallace** [comment]
No worries - I figured how do it based on your suggestion on stackoverflow 

http://stackoverflow.com/questions/32353680/how-to-access-browser-session-cookies-from-within-shiny-app/37615126#37615126

Sample app is here: https://beta.rstudioconnect.com/iwallace/cookies/

**Comment by daattali** [comment]
Cool, good to see that!
