### ISSUE TITLE
V8 new feature and usage within shinyjs

### ISSUE THREAD

**Issue by debsush** [daattali/shinyjs#75]
Dean,

Based on the [article](http://www.r-bloggers.com/new-in-v8-calling-r-from-javascript-from-r-from-javascript/), we can now use v8 and run R script within Javascript. 

Now I have situation where I would like to minimize the transfer of heavy data between my server (R) and my client (mostly JS) by doing the following:
1. First extract data using R and pass it onto JS (client) using following
datajson<-jsonlite::toJSON(DF)
shinyjs::js$JavaFunction(datajson)

Now, I want to perform the remaining computation on the data within the javaFunction.  For certain parts of this computation within javaFunction, I need the help of R and would like to run some R functions within javaFunction

Based on the article referenced above, this seems doable.  So I tried the following:

shinyjs.javaFunction = function(params){
 var data = params[1];
 var out = console.r.call('function(x){x^2}', {x:12})
 alert(out);
} 

Execution of the above function gave me the following error in shiny

 Uncaught TypeError: Cannot read property 'call' of undefined

Please suggest where did I go wrong

Regards
SD

**Comment by daattali** [comment]
The V8 package only works within R. It provides a Javascript engine *inside R*. But the "shinyjs.javaFunction" is defined in pure Javascript,  not in R using V8. I don't think you can do what you're trying to do.

**Comment by debsush** [comment]
Noted.  I am not a big JS guy but I found the below resource.  Was wondering if we could leverage this within the Javascript to run the R scripts.

https://github.com/albertosantini/node-rio

Appreciate your guidance.
Regards
SD

**Comment by daattali** [comment]
I've never used that package, it looks like it can be very powerful but
quite complicated. You can ask them how to use their package or try to read
their documentation, but it's really out of scope for shinyjs, sorry

---
http://deanattali.com

**Comment by debsush** [comment]
Thanks.  I will try that route.

**Comment by debsush** [comment]
I will close this ticket as it does not belong here.

On a separate note, I have a query.  I want to minimize the client server client roundtrip in my app to the extent possible.

If I have all my JS functions in a file "myJS.js" and I include it in my ui. using the below code and then have an input component run a function within "myJS.js", is this all happening on the client side or server-side or a mix of both.  My intention is to have everything on the client side

ui.R  

```
useShinyjs(),
HTML('<button id="ForwardBtn" onclick="shinyjs.ForwardData()" class="round-button">></button>')
  extendShinyjs(script="myJS.js"),
```

Regards
SD

**Comment by daattali** [comment]
Any javascript code that will be running will be happening on the client side (unless you're using V8). The `ForwardData()` function and everything inside `myJS.js` will be happening on the client side. The only thing the server side (R) will do is parse the parameters and pass them to the javascript function

**Comment by debsush** [comment]
the server R will come into the picture if I use something like below in server.R
`shinyjs::onclick("ForwardBtn",js$shinyjs.ForwardData())`
What if I use the below in ui.R, will it still need the server (R) to parse the parameters and pass them to javascript function:
`HTML('<button id="ForwardBtn" onclick="shinyjs.ForwardData()" class="round-button">Button</button>')`

**Comment by daattali** [comment]
Endnotes if you use shinyjs:: onclick like you say here, the only thing
that R will do is call the forwardaData function in Javascript.

**Comment by debsush** [comment]
Agreed.  Thank you
