### ISSUE TITLE
Does shinyjs require R 3.1.2?

### ISSUE THREAD

**Issue by jeffwong** [daattali/shinyjs#8]
I have some servers that are running R 3.1.0, and they cannot run install.packages('shinyjs').  Does your library require R 3.1.2 specifically? From browsing around it doesn't look like you really need anything from 3.1.2, it would be very helpful to remove that requirement and will also make it easier for others to adopt your great work!

**Comment by daattali** [comment]
I don't think 3.1.2 is a strict requirement, it was just what I had when I started developing. I can downgrade that requirement on the github version, but not on the CRAN version
