### ISSUE TITLE
working with other js

### ISSUE THREAD

**Issue by happyshows** [daattali/shinyjs#84]
Hi,

I am trying to use shinyjs to call a tableau js api to embed tableau report inside shiny, however I saw below message.

Error: shinyjs: Error parsing the JavaScript code provided.

```
library(shiny)
library(shinyjs)

jscode <- "
shinyjs.initViz = function() {
var containerDiv = document.getElementById('vizContainer');
var url = 'http://public.tableau.com/views/RegionalSampleWorkbook/Storms';
options = {
hideTabs: true,
onFirstInteractive: function () {
console.log('Run this code when the viz has finished loading.');
};

// Create a viz object and embed it in the container div.
var viz = new tableau.Viz(containerDiv, url, options); 
}"


runApp(shinyApp(
  ui = fluidPage(
    tags$head(HTML("<script type='text/javascript' src='https://public.tableau.com/javascripts/api/tableau-2.js'></script>")),
    useShinyjs(),
    extendShinyjs(text = jsCode),
    actionButton("btn", "Click me"),
    tags$div(id = 'vizContainer')
  ),
  server = function(input, output, session) {
    onclick("btn", {
      js$initViz()
    })
  }
))
```

the reference code for tableau js:
[link](https://github.com/tableau/js-api-samples/blob/master/basicEmbed.html)

**Comment by daattali** [comment]
I haven't looked at your code in detail, but that error means exactly what it says: there was an error parsing the javascript you provided. There is probably a syntax error or some other problem with your javascript. Make sure the javascript code you provide is valid.

**Comment by happyshows** [comment]
Hi,

I tried a different approach to call the code. And I have posted a new issue on SO. Could you verify that it has nothing to do with shinyjs? Then I can close here and address it to Tableau folks.

**Comment by daattali** [comment]
I answered the SO question which is different from what you posted here.

I just looked at the javascript code you posted here, and I do see a syntax error, as shinyjs is telling you is happening. If you paste your javascript code to a browser javascript console, you'll get an error.  You have a missing `}` to close the options variable.

**Comment by happyshows** [comment]
Thanks. I was able to launch a hello world example using document.ready, however I'm still tempted to use shinyjs to pass parameters from shiny to Tableau, as I see the implementation is really neat. Closing this ticket for now.
