### ISSUE TITLE
How to hook into rpivottable via shinyjs

### ISSUE THREAD

**Issue by GaryWMN** [daattali/shinyjs#89]
Dean,
I have a shiny app that uses shinyjs and rpivottable. I want to update the display with a modal dialog (a la the busy dialog in https://gallery.shinyapps.io/107-events/) when the display is dead during a pivottable load or refresh. I'm pretty new to javascript, but with the timeline recorder in Chrome, I've been able to find a few instances of the shinyjs mutation callback function that may indicate points that I can hook into shinyjs (before/after the update) and show/hide the modal dialog. However, I am at a loss for learning how to determine what events (or objects) are causing the mutation function call. Alternatively, if I can learn how to hook into the rpivottable functions or events (or those of the underlying supporting script libraries), that might work too. 
I'm running into the end of my resourcefulness (at least for this week) in researching the huge and vast areas of JS learning. Can you recommend any resources that might help me learn and then help me apply? Not looking for anyone to do the work for me, but I am trying to find the next post (or article) to read. 
Only as you have time.
Thanks!

**Reference**
\<Screenshot of the "hook points" in my app\>
![shinyjsmutationhookpoints](https://cloud.githubusercontent.com/assets/16209437/19658045/102d50ea-99ec-11e6-87a1-407e1b9c5d9a.png)

P.S. If this is not an appropriate use of Issues in shinyjs, please feel free to provide constructive criticism for improvements. Again... thanks!
P.P.S. Saw your talk to RStudio conference in January of this year. Thanks for the excellent package. My colleagues and I find it quite useful.

**Comment by daattali** [comment]
Definitely looks like you've done a lot of homework on this, judging by how deep you dove with that screenshot!  But unfortunately I'm not sure how to help you on this. I don't think this sounds like a shinyjs issue, sounds like a javascript issue, and javascript is very different from R and is a bit harder and scarier to learn..... I don't have any particular resources to share with you, but perhaps try StackOverflow. If you feel like you've spent too much time on this and would like some help in coding a solution, feel free to email me. Sorry I can't be more helpful!

**Comment by GaryWMN** [comment]
Thanks for the feedback. I'll keep working on it. Looks like if I can identify the function used by pivottable.js at those points, I may be able to hook into it? (see ref) Perhaps send a message back to Shiny or trigger the display/hide of the modal dialog. 

Continuing to learn...

Ref: http://stackoverflow.com/a/10273320
