### ISSUE TITLE
clicking function

### ISSUE THREAD

**Issue by yonicd** [daattali/shinyjs#90]
I am qcing a shinyapp and need to automate some clicks and filling in fields to get to the stage i need without wasting time to get there at each restart. onclick is a passive function is there one that is the active version?

**Comment by daattali** [comment]
You just need basic javascript for that - a one liner such as `$("#id").click();` would suffice. This isn't a shinyjs issue though, it's purely javascript, so I'm closing this issue. When you know what javascript code you want to run, you can call it with `shinyjs::runjs(code)`

**Comment by yonicd** [comment]
thanks
