### ISSUE TITLE
JS global variables and Shiny Server

### ISSUE THREAD

**Issue by sanchez5674** [daattali/shinyjs#98]
Hi, 

Note, this is a demo app to highlight the issue. It is not the real code. 

I can define a global variables in shinyjs which is accessible in the entire JS scope and everything runs fine from RStudio --> shinyApp() 

This is ui.R

```
library(shiny)
library(shinyjs)

jsCode <- "
shinyjs.init = function() {
  myGlobal = 7;
};

shinyjs.add = function(amount) {
  var tmp = myGlobal + parseInt(amount);
  
  console.log(tmp);
  Shiny.onInputChange('mySum', tmp);
};"

ui = fluidPage(
  useShinyjs(),
  extendShinyjs(text = jsCode),
  textInput("tSum", "Include Amount:"),
  actionButton("bSum", "Sum!"),
  br(),
  br(),
  textOutput("oSum")
)
```

and this is server.R

```
server = function(input, output, session) {  
  resSum <- reactiveValues(var = NULL)
  
  observeEvent(input$bSum, {
    shinyjs::js$add(input$tSum)

    updateTextInput(session, "tSum", "Include Amount", "")
  })
  
  observe({
    resSum$var <- input$mySum
  })

  output$oSum <- renderText({
    paste("The result of the sum is", resSum$var)
  })
}
```

However, when I run the same app using shiny server I get an error in the JS console saying:

> Uncaught ReferenceError: myGlobal is not defined

How should myGlobal be defined? Thanks for the help. 

Carlos

**Comment by daattali** [comment]
Hi, I just tried adding this app to my own shiny server and it seems to work fine.

https://daattali.com/shiny/jsglobalbug/

Perhaps there's something strange about your shiny server setup? I'm really not sure what this can be, never heard of this issues before and I have no idea why a variable wouldn't be defined globally...

**Comment by sanchez5674** [comment]
Thanks Dean. 

I'll investigate on my side. Not really sure what might be causing this issue. 

Carlos

**Comment by sanchez5674** [comment]
I updated to the new versions of shinyjs and shiny and the problem went away. 

Thanks.
